//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Alliance
{
    using Common.Protocol.Network.Types.Game.Context.Roleplay;
    using System.Collections.Generic;
    using System;
    
    
    public class AllianceInvitedMessage : NetworkMessage
    {
        
        public const int Id = 6397;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private uint m_recruterId;
        
        public virtual uint RecruterId
        {
            get
            {
                return m_recruterId;
            }
            set
            {
                m_recruterId = value;
            }
        }
        
        private string m_recruterName;
        
        public virtual string RecruterName
        {
            get
            {
                return m_recruterName;
            }
            set
            {
                m_recruterName = value;
            }
        }
        
        private BasicNamedAllianceInformations m_allianceInfo;
        
        public virtual BasicNamedAllianceInformations AllianceInfo
        {
            get
            {
                return m_allianceInfo;
            }
            set
            {
                m_allianceInfo = value;
            }
        }
        
        public void Initiate(uint recruterId, string recruterName, BasicNamedAllianceInformations allianceInfo)
        {
            m_recruterId = recruterId;
            m_recruterName = recruterName;
            m_allianceInfo = allianceInfo;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhInt(m_recruterId);
            writer.WriteUTF(m_recruterName);
            m_allianceInfo.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_recruterId = reader.ReadVarUhInt();
            m_recruterName = reader.ReadUTF();
            m_allianceInfo = new BasicNamedAllianceInformations();
            m_allianceInfo.Deserialize(reader);
        }
    }
}
