//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Alliance
{
    using Common.Protocol.Network.Types.Game.Guild;
    using System.Collections.Generic;
    using System;
    
    
    public class AllianceCreationValidMessage : NetworkMessage
    {
        
        public const int Id = 6393;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private string m_allianceName;
        
        public virtual string AllianceName
        {
            get
            {
                return m_allianceName;
            }
            set
            {
                m_allianceName = value;
            }
        }
        
        private string m_allianceTag;
        
        public virtual string AllianceTag
        {
            get
            {
                return m_allianceTag;
            }
            set
            {
                m_allianceTag = value;
            }
        }
        
        private GuildEmblem m_allianceEmblem;
        
        public virtual GuildEmblem AllianceEmblem
        {
            get
            {
                return m_allianceEmblem;
            }
            set
            {
                m_allianceEmblem = value;
            }
        }
        
        public void Initiate(string allianceName, string allianceTag, GuildEmblem allianceEmblem)
        {
            m_allianceName = allianceName;
            m_allianceTag = allianceTag;
            m_allianceEmblem = allianceEmblem;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteUTF(m_allianceName);
            writer.WriteUTF(m_allianceTag);
            m_allianceEmblem.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_allianceName = reader.ReadUTF();
            m_allianceTag = reader.ReadUTF();
            m_allianceEmblem = new GuildEmblem();
            m_allianceEmblem.Deserialize(reader);
        }
    }
}
