//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Roleplay.Houses
{
    using System.Collections.Generic;
    using System;
    
    
    public class HouseSellRequestMessage : NetworkMessage
    {
        
        public const int Id = 5697;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private uint m_amount;
        
        public virtual uint Amount
        {
            get
            {
                return m_amount;
            }
            set
            {
                m_amount = value;
            }
        }
        
        public void Initiate(uint amount)
        {
            m_amount = amount;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhInt(m_amount);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_amount = reader.ReadVarUhInt();
        }
    }
}
