//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Initialization
{
    using System.Collections.Generic;
    using System;
    
    
    public class CharacterCapabilitiesMessage : NetworkMessage
    {
        
        public const int Id = 6339;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private uint m_guildEmblemSymbolCategories;
        
        public virtual uint GuildEmblemSymbolCategories
        {
            get
            {
                return m_guildEmblemSymbolCategories;
            }
            set
            {
                m_guildEmblemSymbolCategories = value;
            }
        }
        
        public void Initiate(uint guildEmblemSymbolCategories)
        {
            m_guildEmblemSymbolCategories = guildEmblemSymbolCategories;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhInt(m_guildEmblemSymbolCategories);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_guildEmblemSymbolCategories = reader.ReadVarUhInt();
        }
    }
}
