//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Initialization
{
    using Common.Protocol.Network.Types.Game.Character.Restriction;
    using System.Collections.Generic;
    using System;
    
    
    public class SetCharacterRestrictionsMessage : NetworkMessage
    {
        
        public const int Id = 170;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private int m_actorId;
        
        public virtual int ActorId
        {
            get
            {
                return m_actorId;
            }
            set
            {
                m_actorId = value;
            }
        }
        
        private ActorRestrictionsInformations m_restrictions;
        
        public virtual ActorRestrictionsInformations Restrictions
        {
            get
            {
                return m_restrictions;
            }
            set
            {
                m_restrictions = value;
            }
        }
        
        public void Initiate(int actorId, ActorRestrictionsInformations restrictions)
        {
            m_actorId = actorId;
            m_restrictions = restrictions;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteInt(m_actorId);
            m_restrictions.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_actorId = reader.ReadInt();
            m_restrictions = new ActorRestrictionsInformations();
            m_restrictions.Deserialize(reader);
        }
    }
}
