//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Data.Items.Effects
{
    using System.Collections.Generic;
    using System;
    
    
    public class ObjectEffectMinMax : ObjectEffect
    {
        
        public const int Id = 82;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private uint m_min;
        
        public virtual uint Min
        {
            get
            {
                return m_min;
            }
            set
            {
                m_min = value;
            }
        }
        
        private uint m_max;
        
        public virtual uint Max
        {
            get
            {
                return m_max;
            }
            set
            {
                m_max = value;
            }
        }
        
        public void Initiate(uint min, uint max)
        {
            m_min = min;
            m_max = max;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhInt(m_min);
            writer.WriteVarUhInt(m_max);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_min = reader.ReadVarUhInt();
            m_max = reader.ReadVarUhInt();
        }
    }
}
