//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Interactive
{
    using Common.Protocol.Network.Types.Game.Interactive;
    using System.Collections.Generic;
    using System;
    
    
    public class InteractiveElementUpdatedMessage : NetworkMessage
    {
        
        public const int Id = 5708;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private InteractiveElement m_interactiveElement;
        
        public virtual InteractiveElement InteractiveElement
        {
            get
            {
                return m_interactiveElement;
            }
            set
            {
                m_interactiveElement = value;
            }
        }
        
        public void Initiate(InteractiveElement interactiveElement)
        {
            m_interactiveElement = interactiveElement;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            m_interactiveElement.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_interactiveElement = new InteractiveElement();
            m_interactiveElement.Deserialize(reader);
        }
    }
}
