//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Inventory.Storage
{
    using Common.Protocol.Network.Types.Game.Data.Items;
    using System.Collections.Generic;
    using System;
    
    
    public class StorageObjectsUpdateMessage : NetworkMessage
    {
        
        public const int Id = 6036;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private List<ObjectItem> m_objectList;
        
        public virtual List<ObjectItem> ObjectList
        {
            get
            {
                return m_objectList;
            }
            set
            {
                m_objectList = value;
            }
        }
        
        public void Initiate(List<ObjectItem> objectList)
        {
            m_objectList = objectList;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteShort(((short)(m_objectList.Count)));
            int objectListIndex;
            for (objectListIndex = 0; (objectListIndex < m_objectList.Count); objectListIndex = (objectListIndex + 1))
            {
                ObjectItem objectToSend = m_objectList[objectListIndex];
                objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            int objectListCount = reader.ReadUShort();
            int objectListIndex;
            m_objectList = new System.Collections.Generic.List<ObjectItem>();
            for (objectListIndex = 0; (objectListIndex < objectListCount); objectListIndex = (objectListIndex + 1))
            {
                ObjectItem objectToAdd = new ObjectItem();
                objectToAdd.Deserialize(reader);
                m_objectList.Add(objectToAdd);
            }
        }
    }
}
