//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Notification
{
    using System.Collections.Generic;
    using System;
    
    
    public class NotificationUpdateFlagMessage : NetworkMessage
    {
        
        public const int Id = 6090;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_index;
        
        public virtual ushort Index
        {
            get
            {
                return m_index;
            }
            set
            {
                m_index = value;
            }
        }
        
        public void Initiate(ushort index)
        {
            m_index = index;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhShort(m_index);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_index = reader.ReadVarUhShort();
        }
    }
}
