//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Inventory.Items
{
    using Common.Protocol.Network.Messages.Game.Inventory.Exchanges;
    using System.Collections.Generic;
    using System;
    
    
    public class ExchangeObjectRemovedFromBagMessage : ExchangeObjectMessage
    {
        
        public const int Id = 6010;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private uint m_objectUID;
        
        public virtual uint ObjectUID
        {
            get
            {
                return m_objectUID;
            }
            set
            {
                m_objectUID = value;
            }
        }
        
        public void Initiate(uint objectUID)
        {
            m_objectUID = objectUID;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhInt(m_objectUID);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_objectUID = reader.ReadVarUhInt();
        }
    }
}
