//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Inventory.Items
{
    using System.Collections.Generic;
    using System;
    
    
    public class InventoryWeightMessage : NetworkMessage
    {
        
        public const int Id = 3009;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private uint m_weight;
        
        public virtual uint Weight
        {
            get
            {
                return m_weight;
            }
            set
            {
                m_weight = value;
            }
        }
        
        private uint m_weightMax;
        
        public virtual uint WeightMax
        {
            get
            {
                return m_weightMax;
            }
            set
            {
                m_weightMax = value;
            }
        }
        
        public void Initiate(uint weight, uint weightMax)
        {
            m_weight = weight;
            m_weightMax = weightMax;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhInt(m_weight);
            writer.WriteVarUhInt(m_weightMax);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_weight = reader.ReadVarUhInt();
            m_weightMax = reader.ReadVarUhInt();
        }
    }
}
