//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Inventory.Items
{
    using System.Collections.Generic;
    using System;
    
    
    public class LivingObjectDissociateMessage : NetworkMessage
    {
        
        public const int Id = 5723;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private uint m_livingUID;
        
        public virtual uint LivingUID
        {
            get
            {
                return m_livingUID;
            }
            set
            {
                m_livingUID = value;
            }
        }
        
        private sbyte m_livingPosition;
        
        public virtual sbyte LivingPosition
        {
            get
            {
                return m_livingPosition;
            }
            set
            {
                m_livingPosition = value;
            }
        }
        
        public void Initiate(uint livingUID, sbyte livingPosition)
        {
            m_livingUID = livingUID;
            m_livingPosition = livingPosition;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhInt(m_livingUID);
            writer.WriteSByte(m_livingPosition);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_livingUID = reader.ReadVarUhInt();
            m_livingPosition = reader.ReadSByte();
        }
    }
}
