//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Inventory.Items
{
    using Common.Protocol.Network.Types.Game.Data.Items;
    using System.Collections.Generic;
    using System;
    
    
    public class MimicryObjectPreviewMessage : NetworkMessage
    {
        
        public const int Id = 6458;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ObjectItem m_result;
        
        public virtual ObjectItem Result
        {
            get
            {
                return m_result;
            }
            set
            {
                m_result = value;
            }
        }
        
        public void Initiate(ObjectItem result)
        {
            m_result = result;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            m_result.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_result = new ObjectItem();
            m_result.Deserialize(reader);
        }
    }
}
