//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Inventory.Items
{
    using Common.Protocol.Network.Types.Game.Data.Items.Effects;
    using Common.Protocol.Network;
    using System.Collections.Generic;
    using System;
    
    
    public class SetUpdateMessage : NetworkMessage
    {
        
        public const int Id = 5503;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_setId;
        
        public virtual ushort SetId
        {
            get
            {
                return m_setId;
            }
            set
            {
                m_setId = value;
            }
        }
        
        private List<System.UInt16> m_setObjects;
        
        public virtual List<System.UInt16> SetObjects
        {
            get
            {
                return m_setObjects;
            }
            set
            {
                m_setObjects = value;
            }
        }
        
        private List<ObjectEffect> m_setEffects;
        
        public virtual List<ObjectEffect> SetEffects
        {
            get
            {
                return m_setEffects;
            }
            set
            {
                m_setEffects = value;
            }
        }
        
        public void Initiate(ushort setId, List<System.UInt16> setObjects, List<ObjectEffect> setEffects)
        {
            m_setId = setId;
            m_setObjects = setObjects;
            m_setEffects = setEffects;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhShort(m_setId);
            writer.WriteShort(((short)(m_setObjects.Count)));
            int setObjectsIndex;
            for (setObjectsIndex = 0; (setObjectsIndex < m_setObjects.Count); setObjectsIndex = (setObjectsIndex + 1))
            {
                writer.WriteVarUhShort(m_setObjects[setObjectsIndex]);
            }
            writer.WriteShort(((short)(m_setEffects.Count)));
            int setEffectsIndex;
            for (setEffectsIndex = 0; (setEffectsIndex < m_setEffects.Count); setEffectsIndex = (setEffectsIndex + 1))
            {
                ObjectEffect objectToSend = m_setEffects[setEffectsIndex];
                writer.WriteUShort(((ushort)(objectToSend.ProtocolId)));
                objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_setId = reader.ReadVarUhShort();
            int setObjectsCount = reader.ReadUShort();
            int setObjectsIndex;
            m_setObjects = new System.Collections.Generic.List<ushort>();
            for (setObjectsIndex = 0; (setObjectsIndex < setObjectsCount); setObjectsIndex = (setObjectsIndex + 1))
            {
                m_setObjects.Add(reader.ReadVarUhShort());
            }
            int setEffectsCount = reader.ReadUShort();
            int setEffectsIndex;
            m_setEffects = new System.Collections.Generic.List<ObjectEffect>();
            for (setEffectsIndex = 0; (setEffectsIndex < setEffectsCount); setEffectsIndex = (setEffectsIndex + 1))
            {
                ObjectEffect objectToAdd = ProtocolManager.GetTypeInstance<ObjectEffect>(reader.ReadUShort());
                objectToAdd.Deserialize(reader);
                m_setEffects.Add(objectToAdd);
            }
        }
    }
}
