//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Data.Items
{
    using Common.Protocol.Network.Types.Game.Data.Items.Effects;
    using Common.Protocol.Network;
    using System.Collections.Generic;
    using System;
    
    
    public class ObjectItemToSellInHumanVendorShop : Item
    {
        
        public const int Id = 359;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_objectGID;
        
        public virtual ushort ObjectGID
        {
            get
            {
                return m_objectGID;
            }
            set
            {
                m_objectGID = value;
            }
        }
        
        private List<ObjectEffect> m_effects;
        
        public virtual List<ObjectEffect> Effects
        {
            get
            {
                return m_effects;
            }
            set
            {
                m_effects = value;
            }
        }
        
        private uint m_objectUID;
        
        public virtual uint ObjectUID
        {
            get
            {
                return m_objectUID;
            }
            set
            {
                m_objectUID = value;
            }
        }
        
        private uint m_quantity;
        
        public virtual uint Quantity
        {
            get
            {
                return m_quantity;
            }
            set
            {
                m_quantity = value;
            }
        }
        
        private uint m_objectPrice;
        
        public virtual uint ObjectPrice
        {
            get
            {
                return m_objectPrice;
            }
            set
            {
                m_objectPrice = value;
            }
        }
        
        private uint m_publicPrice;
        
        public virtual uint PublicPrice
        {
            get
            {
                return m_publicPrice;
            }
            set
            {
                m_publicPrice = value;
            }
        }
        
        public void Initiate(ushort objectGID, List<ObjectEffect> effects, uint objectUID, uint quantity, uint objectPrice, uint publicPrice)
        {
            m_objectGID = objectGID;
            m_effects = effects;
            m_objectUID = objectUID;
            m_quantity = quantity;
            m_objectPrice = objectPrice;
            m_publicPrice = publicPrice;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhShort(m_objectGID);
            writer.WriteShort(((short)(m_effects.Count)));
            int effectsIndex;
            for (effectsIndex = 0; (effectsIndex < m_effects.Count); effectsIndex = (effectsIndex + 1))
            {
                ObjectEffect objectToSend = m_effects[effectsIndex];
                writer.WriteUShort(((ushort)(objectToSend.ProtocolId)));
                objectToSend.Serialize(writer);
            }
            writer.WriteVarUhInt(m_objectUID);
            writer.WriteVarUhInt(m_quantity);
            writer.WriteVarUhInt(m_objectPrice);
            writer.WriteVarUhInt(m_publicPrice);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_objectGID = reader.ReadVarUhShort();
            int effectsCount = reader.ReadUShort();
            int effectsIndex;
            m_effects = new System.Collections.Generic.List<ObjectEffect>();
            for (effectsIndex = 0; (effectsIndex < effectsCount); effectsIndex = (effectsIndex + 1))
            {
                ObjectEffect objectToAdd = ProtocolManager.GetTypeInstance<ObjectEffect>(reader.ReadUShort());
                objectToAdd.Deserialize(reader);
                m_effects.Add(objectToAdd);
            }
            m_objectUID = reader.ReadVarUhInt();
            m_quantity = reader.ReadVarUhInt();
            m_objectPrice = reader.ReadVarUhInt();
            m_publicPrice = reader.ReadVarUhInt();
        }
    }
}
