//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Fight
{
    using System.Collections.Generic;
    using System;
    
    
    public class GameFightTurnListMessage : NetworkMessage
    {
        
        public const int Id = 713;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private List<System.Int32> m_ids;
        
        public virtual List<System.Int32> Ids
        {
            get
            {
                return m_ids;
            }
            set
            {
                m_ids = value;
            }
        }
        
        private List<System.Int32> m_deadsIds;
        
        public virtual List<System.Int32> DeadsIds
        {
            get
            {
                return m_deadsIds;
            }
            set
            {
                m_deadsIds = value;
            }
        }
        
        public void Initiate(List<System.Int32> ids, List<System.Int32> deadsIds)
        {
            m_ids = ids;
            m_deadsIds = deadsIds;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteShort(((short)(m_ids.Count)));
            int idsIndex;
            for (idsIndex = 0; (idsIndex < m_ids.Count); idsIndex = (idsIndex + 1))
            {
                writer.WriteInt(m_ids[idsIndex]);
            }
            writer.WriteShort(((short)(m_deadsIds.Count)));
            int deadsIdsIndex;
            for (deadsIdsIndex = 0; (deadsIdsIndex < m_deadsIds.Count); deadsIdsIndex = (deadsIdsIndex + 1))
            {
                writer.WriteInt(m_deadsIds[deadsIdsIndex]);
            }
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            int idsCount = reader.ReadUShort();
            int idsIndex;
            m_ids = new System.Collections.Generic.List<int>();
            for (idsIndex = 0; (idsIndex < idsCount); idsIndex = (idsIndex + 1))
            {
                m_ids.Add(reader.ReadInt());
            }
            int deadsIdsCount = reader.ReadUShort();
            int deadsIdsIndex;
            m_deadsIds = new System.Collections.Generic.List<int>();
            for (deadsIdsIndex = 0; (deadsIdsIndex < deadsIdsCount); deadsIdsIndex = (deadsIdsIndex + 1))
            {
                m_deadsIds.Add(reader.ReadInt());
            }
        }
    }
}
