//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Fight
{
    using System.Collections.Generic;
    using System;
    
    
    public class GameFightLeaveMessage : NetworkMessage
    {
        
        public const int Id = 721;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private int m_charId;
        
        public virtual int CharId
        {
            get
            {
                return m_charId;
            }
            set
            {
                m_charId = value;
            }
        }
        
        public void Initiate(int charId)
        {
            m_charId = charId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteInt(m_charId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_charId = reader.ReadInt();
        }
    }
}
