//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Fight
{
    using System.Collections.Generic;
    using System;
    
    
    public class GameFightPlacementSwapPositionsCancelledMessage : NetworkMessage
    {
        
        public const int Id = 6546;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private int m_requestId;
        
        public virtual int RequestId
        {
            get
            {
                return m_requestId;
            }
            set
            {
                m_requestId = value;
            }
        }
        
        private uint m_cancellerId;
        
        public virtual uint CancellerId
        {
            get
            {
                return m_cancellerId;
            }
            set
            {
                m_cancellerId = value;
            }
        }
        
        public void Initiate(int requestId, uint cancellerId)
        {
            m_requestId = requestId;
            m_cancellerId = cancellerId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteInt(m_requestId);
            writer.WriteVarUhInt(m_cancellerId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_requestId = reader.ReadInt();
            m_cancellerId = reader.ReadVarUhInt();
        }
    }
}
