//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Fight
{
    using System.Collections.Generic;
    using System;
    
    
    public class GameFightPlacementSwapPositionsRequestMessage : GameFightPlacementPositionRequestMessage
    {
        
        public const int Id = 6541;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private int m_requestedId;
        
        public virtual int RequestedId
        {
            get
            {
                return m_requestedId;
            }
            set
            {
                m_requestedId = value;
            }
        }
        
        public void Initiate(int requestedId)
        {
            m_requestedId = requestedId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteInt(m_requestedId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_requestedId = reader.ReadInt();
        }
    }
}
