//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Fight
{
    using System.Collections.Generic;
    using System;
    
    
    public class GameFightNewWaveMessage : NetworkMessage
    {
        
        public const int Id = 6490;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private byte m_ObjectId;
        
        public virtual byte ObjectId
        {
            get
            {
                return m_ObjectId;
            }
            set
            {
                m_ObjectId = value;
            }
        }
        
        private byte m_teamId;
        
        public virtual byte TeamId
        {
            get
            {
                return m_teamId;
            }
            set
            {
                m_teamId = value;
            }
        }
        
        private short m_nbTurnBeforeNextWave;
        
        public virtual short NbTurnBeforeNextWave
        {
            get
            {
                return m_nbTurnBeforeNextWave;
            }
            set
            {
                m_nbTurnBeforeNextWave = value;
            }
        }
        
        public void Initiate(byte objectId, byte teamId, short nbTurnBeforeNextWave)
        {
            m_ObjectId = objectId;
            m_teamId = teamId;
            m_nbTurnBeforeNextWave = nbTurnBeforeNextWave;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteByte(m_ObjectId);
            writer.WriteByte(m_teamId);
            writer.WriteShort(m_nbTurnBeforeNextWave);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_ObjectId = reader.ReadByte();
            m_teamId = reader.ReadByte();
            m_nbTurnBeforeNextWave = reader.ReadShort();
        }
    }
}
