//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Fight
{
    using System.Collections.Generic;
    using System;
    
    
    public class GameFightRemoveTeamMemberMessage : NetworkMessage
    {
        
        public const int Id = 711;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private short m_fightId;
        
        public virtual short FightId
        {
            get
            {
                return m_fightId;
            }
            set
            {
                m_fightId = value;
            }
        }
        
        private byte m_teamId;
        
        public virtual byte TeamId
        {
            get
            {
                return m_teamId;
            }
            set
            {
                m_teamId = value;
            }
        }
        
        private int m_charId;
        
        public virtual int CharId
        {
            get
            {
                return m_charId;
            }
            set
            {
                m_charId = value;
            }
        }
        
        public void Initiate(short fightId, byte teamId, int charId)
        {
            m_fightId = fightId;
            m_teamId = teamId;
            m_charId = charId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteShort(m_fightId);
            writer.WriteByte(m_teamId);
            writer.WriteInt(m_charId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_fightId = reader.ReadShort();
            m_teamId = reader.ReadByte();
            m_charId = reader.ReadInt();
        }
    }
}
