//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Character.Choice
{
    using Common.Protocol.Network.Messages.Game.Character.Replay;
    using Common.Protocol.Network.Types.Game.Character.Choice;
    using System.Collections.Generic;
    using System;
    
    
    public class CharacterReplayWithRemodelRequestMessage : CharacterReplayRequestMessage
    {
        
        public const int Id = 6551;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private RemodelingInformation m_remodel;
        
        public virtual RemodelingInformation Remodel
        {
            get
            {
                return m_remodel;
            }
            set
            {
                m_remodel = value;
            }
        }
        
        public void Initiate(RemodelingInformation remodel)
        {
            m_remodel = remodel;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            m_remodel.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_remodel = new RemodelingInformation();
            m_remodel.Deserialize(reader);
        }
    }
}
