//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Character.Choice
{
    using Common.Protocol.Network.Types.Game.Character.Choice;
    using System.Collections.Generic;
    using System;
    
    
    public class CharacterSelectedSuccessMessage : NetworkMessage
    {
        
        public const int Id = 153;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private CharacterBaseInformations m_infos;
        
        public virtual CharacterBaseInformations Infos
        {
            get
            {
                return m_infos;
            }
            set
            {
                m_infos = value;
            }
        }
        
        private bool m_isCollectingStats;
        
        public virtual bool IsCollectingStats
        {
            get
            {
                return m_isCollectingStats;
            }
            set
            {
                m_isCollectingStats = value;
            }
        }
        
        public void Initiate(CharacterBaseInformations infos, bool isCollectingStats)
        {
            m_infos = infos;
            m_isCollectingStats = isCollectingStats;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            m_infos.Serialize(writer);
            writer.WriteBoolean(m_isCollectingStats);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_infos = new CharacterBaseInformations();
            m_infos.Deserialize(reader);
            m_isCollectingStats = reader.ReadBoolean();
        }
    }
}
