//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Paddock
{
    using System.Collections.Generic;
    using System;
    
    
    public class MountInformationsForPaddock : NetworkType
    {
        
        public const int Id = 184;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private byte m_modelId;
        
        public virtual byte ModelId
        {
            get
            {
                return m_modelId;
            }
            set
            {
                m_modelId = value;
            }
        }
        
        private string m_name;
        
        public virtual string Name
        {
            get
            {
                return m_name;
            }
            set
            {
                m_name = value;
            }
        }
        
        private string m_ownerName;
        
        public virtual string OwnerName
        {
            get
            {
                return m_ownerName;
            }
            set
            {
                m_ownerName = value;
            }
        }
        
        public void Initiate(byte modelId, string name, string ownerName)
        {
            m_modelId = modelId;
            m_name = name;
            m_ownerName = ownerName;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteByte(m_modelId);
            writer.WriteUTF(m_name);
            writer.WriteUTF(m_ownerName);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_modelId = reader.ReadByte();
            m_name = reader.ReadUTF();
            m_ownerName = reader.ReadUTF();
        }
    }
}
