//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Roleplay.Emote
{
    using System.Collections.Generic;
    using System;
    
    
    public class EmotePlayMassiveMessage : EmotePlayAbstractMessage
    {
        
        public const int Id = 5691;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private List<System.Int32> m_actorIds;
        
        public virtual List<System.Int32> ActorIds
        {
            get
            {
                return m_actorIds;
            }
            set
            {
                m_actorIds = value;
            }
        }
        
        public void Initiate(List<System.Int32> actorIds)
        {
            m_actorIds = actorIds;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort(((short)(m_actorIds.Count)));
            int actorIdsIndex;
            for (actorIdsIndex = 0; (actorIdsIndex < m_actorIds.Count); actorIdsIndex = (actorIdsIndex + 1))
            {
                writer.WriteInt(m_actorIds[actorIdsIndex]);
            }
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            int actorIdsCount = reader.ReadUShort();
            int actorIdsIndex;
            m_actorIds = new System.Collections.Generic.List<int>();
            for (actorIdsIndex = 0; (actorIdsIndex < actorIdsCount); actorIdsIndex = (actorIdsIndex + 1))
            {
                m_actorIds.Add(reader.ReadInt());
            }
        }
    }
}
