//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Character.Alignment
{
    using System.Collections.Generic;
    using System;
    
    
    public class ActorAlignmentInformations : NetworkType
    {
        
        public const int Id = 201;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private byte m_alignmentSide;
        
        public virtual byte AlignmentSide
        {
            get
            {
                return m_alignmentSide;
            }
            set
            {
                m_alignmentSide = value;
            }
        }
        
        private byte m_alignmentValue;
        
        public virtual byte AlignmentValue
        {
            get
            {
                return m_alignmentValue;
            }
            set
            {
                m_alignmentValue = value;
            }
        }
        
        private byte m_alignmentGrade;
        
        public virtual byte AlignmentGrade
        {
            get
            {
                return m_alignmentGrade;
            }
            set
            {
                m_alignmentGrade = value;
            }
        }
        
        private uint m_characterPower;
        
        public virtual uint CharacterPower
        {
            get
            {
                return m_characterPower;
            }
            set
            {
                m_characterPower = value;
            }
        }
        
        public void Initiate(byte alignmentSide, byte alignmentValue, byte alignmentGrade, uint characterPower)
        {
            m_alignmentSide = alignmentSide;
            m_alignmentValue = alignmentValue;
            m_alignmentGrade = alignmentGrade;
            m_characterPower = characterPower;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteByte(m_alignmentSide);
            writer.WriteByte(m_alignmentValue);
            writer.WriteByte(m_alignmentGrade);
            writer.WriteVarUhInt(m_characterPower);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_alignmentSide = reader.ReadByte();
            m_alignmentValue = reader.ReadByte();
            m_alignmentGrade = reader.ReadByte();
            m_characterPower = reader.ReadVarUhInt();
        }
    }
}
