//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Guild.Tax
{
    using Common.Protocol.Network.Types.Game.Guild.Tax;
    using Common.Protocol.Network;
    using System.Collections.Generic;
    using System;
    
    
    public class AbstractTaxCollectorListMessage : NetworkMessage
    {
        
        public const int Id = 6568;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private List<TaxCollectorInformations> m_informations;
        
        public virtual List<TaxCollectorInformations> Informations
        {
            get
            {
                return m_informations;
            }
            set
            {
                m_informations = value;
            }
        }
        
        public void Initiate(List<TaxCollectorInformations> informations)
        {
            m_informations = informations;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteShort(((short)(m_informations.Count)));
            int informationsIndex;
            for (informationsIndex = 0; (informationsIndex < m_informations.Count); informationsIndex = (informationsIndex + 1))
            {
                TaxCollectorInformations objectToSend = m_informations[informationsIndex];
                writer.WriteUShort(((ushort)(objectToSend.ProtocolId)));
                objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            int informationsCount = reader.ReadUShort();
            int informationsIndex;
            m_informations = new System.Collections.Generic.List<TaxCollectorInformations>();
            for (informationsIndex = 0; (informationsIndex < informationsCount); informationsIndex = (informationsIndex + 1))
            {
                TaxCollectorInformations objectToAdd = ProtocolManager.GetTypeInstance<TaxCollectorInformations>(reader.ReadUShort());
                objectToAdd.Deserialize(reader);
                m_informations.Add(objectToAdd);
            }
        }
    }
}
