//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Guild.Tax
{
    using System.Collections.Generic;
    using System;
    
    
    public class GuildFightTakePlaceRequestMessage : GuildFightJoinRequestMessage
    {
        
        public const int Id = 6235;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private int m_replacedCharacterId;
        
        public virtual int ReplacedCharacterId
        {
            get
            {
                return m_replacedCharacterId;
            }
            set
            {
                m_replacedCharacterId = value;
            }
        }
        
        public void Initiate(int replacedCharacterId)
        {
            m_replacedCharacterId = replacedCharacterId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteInt(m_replacedCharacterId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_replacedCharacterId = reader.ReadInt();
        }
    }
}
