//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Guild.Tax
{
    using Common.Protocol.Network.Types.Game.Guild.Tax;
    using System.Collections.Generic;
    using System;
    
    
    public class TaxCollectorMovementMessage : NetworkMessage
    {
        
        public const int Id = 5633;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private bool m_hireOrFire;
        
        public virtual bool HireOrFire
        {
            get
            {
                return m_hireOrFire;
            }
            set
            {
                m_hireOrFire = value;
            }
        }
        
        private TaxCollectorBasicInformations m_basicInfos;
        
        public virtual TaxCollectorBasicInformations BasicInfos
        {
            get
            {
                return m_basicInfos;
            }
            set
            {
                m_basicInfos = value;
            }
        }
        
        private uint m_playerId;
        
        public virtual uint PlayerId
        {
            get
            {
                return m_playerId;
            }
            set
            {
                m_playerId = value;
            }
        }
        
        private string m_playerName;
        
        public virtual string PlayerName
        {
            get
            {
                return m_playerName;
            }
            set
            {
                m_playerName = value;
            }
        }
        
        public void Initiate(bool hireOrFire, TaxCollectorBasicInformations basicInfos, uint playerId, string playerName)
        {
            m_hireOrFire = hireOrFire;
            m_basicInfos = basicInfos;
            m_playerId = playerId;
            m_playerName = playerName;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteBoolean(m_hireOrFire);
            m_basicInfos.Serialize(writer);
            writer.WriteVarUhInt(m_playerId);
            writer.WriteUTF(m_playerName);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_hireOrFire = reader.ReadBoolean();
            m_basicInfos = new TaxCollectorBasicInformations();
            m_basicInfos.Deserialize(reader);
            m_playerId = reader.ReadVarUhInt();
            m_playerName = reader.ReadUTF();
        }
    }
}
