//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Protocol.Messages.Connection
{
    using System.Collections.Generic;
    using System;
    using Protocol.IO.BigEndian;
    
    
    public class SelectedServerRefusedMessage : AbstractNetworkMessage
    {
        
        public const int Id = 41;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_serverId;
        
        public virtual ushort ServerId
        {
            get
            {
                return m_serverId;
            }
            set
            {
                m_serverId = value;
            }
        }
        
        private byte m_error;
        
        public virtual byte Error
        {
            get
            {
                return m_error;
            }
            set
            {
                m_error = value;
            }
        }
        
        private byte m_serverStatus;
        
        public virtual byte ServerStatus
        {
            get
            {
                return m_serverStatus;
            }
            set
            {
                m_serverStatus = value;
            }
        }
        
        public void Initiate(ushort serverId, byte error, byte serverStatus)
        {
            m_serverId = serverId;
            m_error = error;
            m_serverStatus = serverStatus;
        }
        
        public override void Serialize(BigEndianWriter writer)
        {
            writer.WriteVarUhShort(m_serverId);
            writer.WriteByte(m_error);
            writer.WriteByte(m_serverStatus);
        }
        
        public override void Deserialize(BigEndianReader reader)
        {
            m_serverId = reader.ReadVarUhShort();
            m_error = reader.ReadByte();
            m_serverStatus = reader.ReadByte();
        }
    }
}
