//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Roleplay.TreasureHunt
{
    using System.Collections.Generic;
    using System;
    
    
    public class TreasureHuntLegendaryRequestMessage : NetworkMessage
    {
        
        public const int Id = 6499;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_legendaryId;
        
        public virtual ushort LegendaryId
        {
            get
            {
                return m_legendaryId;
            }
            set
            {
                m_legendaryId = value;
            }
        }
        
        public void Initiate(ushort legendaryId)
        {
            m_legendaryId = legendaryId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhShort(m_legendaryId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_legendaryId = reader.ReadVarUhShort();
        }
    }
}
