//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Roleplay.TreasureHunt
{
    using System.Collections.Generic;
    using System;
    
    
    public class TreasureHuntDigRequestAnswerFailedMessage : TreasureHuntDigRequestAnswerMessage
    {
        
        public const int Id = 6509;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private byte m_wrongFlagCount;
        
        public virtual byte WrongFlagCount
        {
            get
            {
                return m_wrongFlagCount;
            }
            set
            {
                m_wrongFlagCount = value;
            }
        }
        
        public void Initiate(byte wrongFlagCount)
        {
            m_wrongFlagCount = wrongFlagCount;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteByte(m_wrongFlagCount);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_wrongFlagCount = reader.ReadByte();
        }
    }
}
