//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Roleplay.TreasureHunt
{
    using System.Collections.Generic;
    using System;
    
    
    public class TreasureHuntRequestMessage : NetworkMessage
    {
        
        public const int Id = 6488;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private sbyte m_questLevel;
        
        public virtual sbyte QuestLevel
        {
            get
            {
                return m_questLevel;
            }
            set
            {
                m_questLevel = value;
            }
        }
        
        private byte m_questType;
        
        public virtual byte QuestType
        {
            get
            {
                return m_questType;
            }
            set
            {
                m_questType = value;
            }
        }
        
        public void Initiate(sbyte questLevel, byte questType)
        {
            m_questLevel = questLevel;
            m_questType = questType;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteSByte(m_questLevel);
            writer.WriteByte(m_questType);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_questLevel = reader.ReadSByte();
            m_questType = reader.ReadByte();
        }
    }
}
