//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Startup
{
    using System.Collections.Generic;
    using System;
    
    
    public class StartupActionsObjetAttributionMessage : NetworkMessage
    {
        
        public const int Id = 1303;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private int m_actionId;
        
        public virtual int ActionId
        {
            get
            {
                return m_actionId;
            }
            set
            {
                m_actionId = value;
            }
        }
        
        private int m_characterId;
        
        public virtual int CharacterId
        {
            get
            {
                return m_characterId;
            }
            set
            {
                m_characterId = value;
            }
        }
        
        public void Initiate(int actionId, int characterId)
        {
            m_actionId = actionId;
            m_characterId = characterId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteInt(m_actionId);
            writer.WriteInt(m_characterId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_actionId = reader.ReadInt();
            m_characterId = reader.ReadInt();
        }
    }
}
