//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Startup
{
    using System.Collections.Generic;
    using System;
    
    
    public class StartupActionFinishedMessage : NetworkMessage
    {
        
        public const int Id = 1304;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private bool m_success;
        
        public virtual bool Success
        {
            get
            {
                return m_success;
            }
            set
            {
                m_success = value;
            }
        }
        
        private bool m_automaticAction;
        
        public virtual bool AutomaticAction
        {
            get
            {
                return m_automaticAction;
            }
            set
            {
                m_automaticAction = value;
            }
        }
        
        private int m_actionId;
        
        public virtual int ActionId
        {
            get
            {
                return m_actionId;
            }
            set
            {
                m_actionId = value;
            }
        }
        
        public void Initiate(bool success, bool automaticAction, int actionId)
        {
            m_success = success;
            m_automaticAction = automaticAction;
            m_actionId = actionId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            byte flag = new byte();
            BooleanByteWrapper.SetFlag(0, flag, m_success);
            BooleanByteWrapper.SetFlag(1, flag, m_automaticAction);
            writer.WriteByte(flag);
            writer.WriteInt(m_actionId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            byte flag = reader.ReadByte();
            m_success = BooleanByteWrapper.GetFlag(flag, 0);
            m_automaticAction = BooleanByteWrapper.GetFlag(flag, 1);
            m_actionId = reader.ReadInt();
        }
    }
}
