//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Inventory.Preset
{
    using System.Collections.Generic;
    using System;
    
    
    public class InventoryPresetUseResultMessage : NetworkMessage
    {
        
        public const int Id = 6163;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private byte m_presetId;
        
        public virtual byte PresetId
        {
            get
            {
                return m_presetId;
            }
            set
            {
                m_presetId = value;
            }
        }
        
        private byte m_code;
        
        public virtual byte Code
        {
            get
            {
                return m_code;
            }
            set
            {
                m_code = value;
            }
        }
        
        private List<System.SByte> m_unlinkedPosition;
        
        public virtual List<System.SByte> UnlinkedPosition
        {
            get
            {
                return m_unlinkedPosition;
            }
            set
            {
                m_unlinkedPosition = value;
            }
        }
        
        public void Initiate(byte presetId, byte code, List<System.SByte> unlinkedPosition)
        {
            m_presetId = presetId;
            m_code = code;
            m_unlinkedPosition = unlinkedPosition;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteByte(m_presetId);
            writer.WriteByte(m_code);
            writer.WriteShort(((short)(m_unlinkedPosition.Count)));
            int unlinkedPositionIndex;
            for (unlinkedPositionIndex = 0; (unlinkedPositionIndex < m_unlinkedPosition.Count); unlinkedPositionIndex = (unlinkedPositionIndex + 1))
            {
                writer.WriteSByte(m_unlinkedPosition[unlinkedPositionIndex]);
            }
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_presetId = reader.ReadByte();
            m_code = reader.ReadByte();
            int unlinkedPositionCount = reader.ReadUShort();
            int unlinkedPositionIndex;
            m_unlinkedPosition = new System.Collections.Generic.List<sbyte>();
            for (unlinkedPositionIndex = 0; (unlinkedPositionIndex < unlinkedPositionCount); unlinkedPositionIndex = (unlinkedPositionIndex + 1))
            {
                m_unlinkedPosition.Add(reader.ReadSByte());
            }
        }
    }
}
