//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Inventory.Preset
{
    using System.Collections.Generic;
    using System;
    
    
    public class InventoryPresetItemUpdateRequestMessage : NetworkMessage
    {
        
        public const int Id = 6210;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private byte m_presetId;
        
        public virtual byte PresetId
        {
            get
            {
                return m_presetId;
            }
            set
            {
                m_presetId = value;
            }
        }
        
        private sbyte m_position;
        
        public virtual sbyte Position
        {
            get
            {
                return m_position;
            }
            set
            {
                m_position = value;
            }
        }
        
        private uint m_objUid;
        
        public virtual uint ObjUid
        {
            get
            {
                return m_objUid;
            }
            set
            {
                m_objUid = value;
            }
        }
        
        public void Initiate(byte presetId, sbyte position, uint objUid)
        {
            m_presetId = presetId;
            m_position = position;
            m_objUid = objUid;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteByte(m_presetId);
            writer.WriteSByte(m_position);
            writer.WriteVarUhInt(m_objUid);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_presetId = reader.ReadByte();
            m_position = reader.ReadSByte();
            m_objUid = reader.ReadVarUhInt();
        }
    }
}
