//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Inventory.Preset
{
    using System.Collections.Generic;
    using System;
    
    
    public class InventoryPresetSaveResultMessage : NetworkMessage
    {
        
        public const int Id = 6170;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private byte m_presetId;
        
        public virtual byte PresetId
        {
            get
            {
                return m_presetId;
            }
            set
            {
                m_presetId = value;
            }
        }
        
        private byte m_code;
        
        public virtual byte Code
        {
            get
            {
                return m_code;
            }
            set
            {
                m_code = value;
            }
        }
        
        public void Initiate(byte presetId, byte code)
        {
            m_presetId = presetId;
            m_code = code;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteByte(m_presetId);
            writer.WriteByte(m_code);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_presetId = reader.ReadByte();
            m_code = reader.ReadByte();
        }
    }
}
