//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Chat.Smiley
{
    using System.Collections.Generic;
    using System;
    
    
    public class ChatSmileyRequestMessage : NetworkMessage
    {
        
        public const int Id = 800;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private byte m_smileyId;
        
        public virtual byte SmileyId
        {
            get
            {
                return m_smileyId;
            }
            set
            {
                m_smileyId = value;
            }
        }
        
        public void Initiate(byte smileyId)
        {
            m_smileyId = smileyId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteByte(m_smileyId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_smileyId = reader.ReadByte();
        }
    }
}
