//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Chat.Smiley
{
    using System.Collections.Generic;
    using System;
    
    
    public class MoodSmileyUpdateMessage : NetworkMessage
    {
        
        public const int Id = 6388;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private int m_accountId;
        
        public virtual int AccountId
        {
            get
            {
                return m_accountId;
            }
            set
            {
                m_accountId = value;
            }
        }
        
        private uint m_playerId;
        
        public virtual uint PlayerId
        {
            get
            {
                return m_playerId;
            }
            set
            {
                m_playerId = value;
            }
        }
        
        private byte m_smileyId;
        
        public virtual byte SmileyId
        {
            get
            {
                return m_smileyId;
            }
            set
            {
                m_smileyId = value;
            }
        }
        
        public void Initiate(int accountId, uint playerId, byte smileyId)
        {
            m_accountId = accountId;
            m_playerId = playerId;
            m_smileyId = smileyId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteInt(m_accountId);
            writer.WriteVarUhInt(m_playerId);
            writer.WriteByte(m_smileyId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_accountId = reader.ReadInt();
            m_playerId = reader.ReadVarUhInt();
            m_smileyId = reader.ReadByte();
        }
    }
}
