//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Roleplay
{
    using System.Collections.Generic;
    using System;
    
    
    public class MapFightCountMessage : NetworkMessage
    {
        
        public const int Id = 210;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_fightCount;
        
        public virtual ushort FightCount
        {
            get
            {
                return m_fightCount;
            }
            set
            {
                m_fightCount = value;
            }
        }
        
        public void Initiate(ushort fightCount)
        {
            m_fightCount = fightCount;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhShort(m_fightCount);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_fightCount = reader.ReadVarUhShort();
        }
    }
}
