//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Queues
{
    using System.Collections.Generic;
    using System;
    
    
    public class QueueStatusMessage : NetworkMessage
    {
        
        public const int Id = 6100;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_position;
        
        public virtual ushort Position
        {
            get
            {
                return m_position;
            }
            set
            {
                m_position = value;
            }
        }
        
        private ushort m_total;
        
        public virtual ushort Total
        {
            get
            {
                return m_total;
            }
            set
            {
                m_total = value;
            }
        }
        
        public void Initiate(ushort position, ushort total)
        {
            m_position = position;
            m_total = total;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteUShort(m_position);
            writer.WriteUShort(m_total);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_position = reader.ReadUShort();
            m_total = reader.ReadUShort();
        }
    }
}
