//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Roleplay.Party
{
    using Common.Protocol.Network.Types.Game.Context.Roleplay.Party;
    using System.Collections.Generic;
    using System;
    
    
    public class DungeonPartyFinderRoomContentMessage : NetworkMessage
    {
        
        public const int Id = 6247;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_dungeonId;
        
        public virtual ushort DungeonId
        {
            get
            {
                return m_dungeonId;
            }
            set
            {
                m_dungeonId = value;
            }
        }
        
        private List<DungeonPartyFinderPlayer> m_players;
        
        public virtual List<DungeonPartyFinderPlayer> Players
        {
            get
            {
                return m_players;
            }
            set
            {
                m_players = value;
            }
        }
        
        public void Initiate(ushort dungeonId, List<DungeonPartyFinderPlayer> players)
        {
            m_dungeonId = dungeonId;
            m_players = players;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhShort(m_dungeonId);
            writer.WriteShort(((short)(m_players.Count)));
            int playersIndex;
            for (playersIndex = 0; (playersIndex < m_players.Count); playersIndex = (playersIndex + 1))
            {
                DungeonPartyFinderPlayer objectToSend = m_players[playersIndex];
                objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_dungeonId = reader.ReadVarUhShort();
            int playersCount = reader.ReadUShort();
            int playersIndex;
            m_players = new System.Collections.Generic.List<DungeonPartyFinderPlayer>();
            for (playersIndex = 0; (playersIndex < playersCount); playersIndex = (playersIndex + 1))
            {
                DungeonPartyFinderPlayer objectToAdd = new DungeonPartyFinderPlayer();
                objectToAdd.Deserialize(reader);
                m_players.Add(objectToAdd);
            }
        }
    }
}
