//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Roleplay.Party
{
    using System.Collections.Generic;
    using System;
    
    
    public class PartyMemberRemoveMessage : AbstractPartyEventMessage
    {
        
        public const int Id = 5579;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private uint m_leavingPlayerId;
        
        public virtual uint LeavingPlayerId
        {
            get
            {
                return m_leavingPlayerId;
            }
            set
            {
                m_leavingPlayerId = value;
            }
        }
        
        public void Initiate(uint leavingPlayerId)
        {
            m_leavingPlayerId = leavingPlayerId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhInt(m_leavingPlayerId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_leavingPlayerId = reader.ReadVarUhInt();
        }
    }
}
