//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Roleplay.Party
{
    using System.Collections.Generic;
    using System;
    
    
    public class PartyLoyaltyStatusMessage : AbstractPartyMessage
    {
        
        public const int Id = 6270;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private bool m_loyal;
        
        public virtual bool Loyal
        {
            get
            {
                return m_loyal;
            }
            set
            {
                m_loyal = value;
            }
        }
        
        public void Initiate(bool loyal)
        {
            m_loyal = loyal;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteBoolean(m_loyal);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_loyal = reader.ReadBoolean();
        }
    }
}
