//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Roleplay.Party
{
    using Common.Protocol.Network.Types.Game.Context.Roleplay.Party;
    using System.Collections.Generic;
    using System;
    
    
    public class PartyNewGuestMessage : AbstractPartyEventMessage
    {
        
        public const int Id = 6260;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private PartyGuestInformations m_guest;
        
        public virtual PartyGuestInformations Guest
        {
            get
            {
                return m_guest;
            }
            set
            {
                m_guest = value;
            }
        }
        
        public void Initiate(PartyGuestInformations guest)
        {
            m_guest = guest;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            m_guest.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_guest = new PartyGuestInformations();
            m_guest.Deserialize(reader);
        }
    }
}
