//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Prism
{
    using System.Collections.Generic;
    using System;
    
    
    public class PrismsListRegisterMessage : NetworkMessage
    {
        
        public const int Id = 6441;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private byte m_listen;
        
        public virtual byte Listen
        {
            get
            {
                return m_listen;
            }
            set
            {
                m_listen = value;
            }
        }
        
        public void Initiate(byte listen)
        {
            m_listen = listen;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteByte(m_listen);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_listen = reader.ReadByte();
        }
    }
}
