//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Prism
{
    using System.Collections.Generic;
    using System;
    
    
    public class PrismFightDefenderLeaveMessage : NetworkMessage
    {
        
        public const int Id = 5892;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_subAreaId;
        
        public virtual ushort SubAreaId
        {
            get
            {
                return m_subAreaId;
            }
            set
            {
                m_subAreaId = value;
            }
        }
        
        private ushort m_fightId;
        
        public virtual ushort FightId
        {
            get
            {
                return m_fightId;
            }
            set
            {
                m_fightId = value;
            }
        }
        
        private uint m_fighterToRemoveId;
        
        public virtual uint FighterToRemoveId
        {
            get
            {
                return m_fighterToRemoveId;
            }
            set
            {
                m_fighterToRemoveId = value;
            }
        }
        
        public void Initiate(ushort subAreaId, ushort fightId, uint fighterToRemoveId)
        {
            m_subAreaId = subAreaId;
            m_fightId = fightId;
            m_fighterToRemoveId = fighterToRemoveId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhShort(m_subAreaId);
            writer.WriteVarUhShort(m_fightId);
            writer.WriteVarUhInt(m_fighterToRemoveId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_subAreaId = reader.ReadVarUhShort();
            m_fightId = reader.ReadVarUhShort();
            m_fighterToRemoveId = reader.ReadVarUhInt();
        }
    }
}
