//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Roleplay.Paddock
{
    using Common.Protocol.Network.Types.Game.Paddock;
    using Common.Protocol.Network;
    using System.Collections.Generic;
    using System;
    
    
    public class PaddockPropertiesMessage : NetworkMessage
    {
        
        public const int Id = 5824;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private PaddockInformations m_properties;
        
        public virtual PaddockInformations Properties
        {
            get
            {
                return m_properties;
            }
            set
            {
                m_properties = value;
            }
        }
        
        public void Initiate(PaddockInformations properties)
        {
            m_properties = properties;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteUShort(((ushort)(m_properties.ProtocolId)));
            m_properties.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_properties = ProtocolManager.GetTypeInstance<PaddockInformations>(reader.ReadUShort());
            m_properties.Deserialize(reader);
        }
    }
}
