//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Guild
{
    using System.Collections.Generic;
    using System;
    
    
    public class GuildCharacsUpgradeRequestMessage : NetworkMessage
    {
        
        public const int Id = 5706;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private byte m_charaTypeTarget;
        
        public virtual byte CharaTypeTarget
        {
            get
            {
                return m_charaTypeTarget;
            }
            set
            {
                m_charaTypeTarget = value;
            }
        }
        
        public void Initiate(byte charaTypeTarget)
        {
            m_charaTypeTarget = charaTypeTarget;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteByte(m_charaTypeTarget);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_charaTypeTarget = reader.ReadByte();
        }
    }
}
