//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Guild
{
    using Common.Protocol.Network.Types.Game.Guild;
    using System.Collections.Generic;
    using System;
    
    
    public class GuildModificationEmblemValidMessage : NetworkMessage
    {
        
        public const int Id = 6328;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private GuildEmblem m_guildEmblem;
        
        public virtual GuildEmblem GuildEmblem
        {
            get
            {
                return m_guildEmblem;
            }
            set
            {
                m_guildEmblem = value;
            }
        }
        
        public void Initiate(GuildEmblem guildEmblem)
        {
            m_guildEmblem = guildEmblem;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            m_guildEmblem.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_guildEmblem = new GuildEmblem();
            m_guildEmblem.Deserialize(reader);
        }
    }
}
