//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Guild
{
    using System.Collections.Generic;
    using System;
    
    
    public class GuildInformationsGeneralMessage : NetworkMessage
    {
        
        public const int Id = 5557;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private bool m_enabled;
        
        public virtual bool Enabled
        {
            get
            {
                return m_enabled;
            }
            set
            {
                m_enabled = value;
            }
        }
        
        private bool m_abandonnedPaddock;
        
        public virtual bool AbandonnedPaddock
        {
            get
            {
                return m_abandonnedPaddock;
            }
            set
            {
                m_abandonnedPaddock = value;
            }
        }
        
        private sbyte m_level;
        
        public virtual sbyte Level
        {
            get
            {
                return m_level;
            }
            set
            {
                m_level = value;
            }
        }
        
        private ulong m_expLevelFloor;
        
        public virtual ulong ExpLevelFloor
        {
            get
            {
                return m_expLevelFloor;
            }
            set
            {
                m_expLevelFloor = value;
            }
        }
        
        private ulong m_experience;
        
        public virtual ulong Experience
        {
            get
            {
                return m_experience;
            }
            set
            {
                m_experience = value;
            }
        }
        
        private ulong m_expNextLevelFloor;
        
        public virtual ulong ExpNextLevelFloor
        {
            get
            {
                return m_expNextLevelFloor;
            }
            set
            {
                m_expNextLevelFloor = value;
            }
        }
        
        private int m_creationDate;
        
        public virtual int CreationDate
        {
            get
            {
                return m_creationDate;
            }
            set
            {
                m_creationDate = value;
            }
        }
        
        private ushort m_nbTotalMembers;
        
        public virtual ushort NbTotalMembers
        {
            get
            {
                return m_nbTotalMembers;
            }
            set
            {
                m_nbTotalMembers = value;
            }
        }
        
        private ushort m_nbConnectedMembers;
        
        public virtual ushort NbConnectedMembers
        {
            get
            {
                return m_nbConnectedMembers;
            }
            set
            {
                m_nbConnectedMembers = value;
            }
        }
        
        public void Initiate(bool enabled, bool abandonnedPaddock, sbyte level, ulong expLevelFloor, ulong experience, ulong expNextLevelFloor, int creationDate, ushort nbTotalMembers, ushort nbConnectedMembers)
        {
            m_enabled = enabled;
            m_abandonnedPaddock = abandonnedPaddock;
            m_level = level;
            m_expLevelFloor = expLevelFloor;
            m_experience = experience;
            m_expNextLevelFloor = expNextLevelFloor;
            m_creationDate = creationDate;
            m_nbTotalMembers = nbTotalMembers;
            m_nbConnectedMembers = nbConnectedMembers;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            byte flag = new byte();
            BooleanByteWrapper.SetFlag(0, flag, m_enabled);
            BooleanByteWrapper.SetFlag(1, flag, m_abandonnedPaddock);
            writer.WriteByte(flag);
            writer.WriteSByte(m_level);
            writer.WriteVarUhLong(m_expLevelFloor);
            writer.WriteVarUhLong(m_experience);
            writer.WriteVarUhLong(m_expNextLevelFloor);
            writer.WriteInt(m_creationDate);
            writer.WriteVarUhShort(m_nbTotalMembers);
            writer.WriteVarUhShort(m_nbConnectedMembers);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            byte flag = reader.ReadByte();
            m_enabled = BooleanByteWrapper.GetFlag(flag, 0);
            m_abandonnedPaddock = BooleanByteWrapper.GetFlag(flag, 1);
            m_level = reader.ReadSByte();
            m_expLevelFloor = reader.ReadVarUhLong();
            m_experience = reader.ReadVarUhLong();
            m_expNextLevelFloor = reader.ReadVarUhLong();
            m_creationDate = reader.ReadInt();
            m_nbTotalMembers = reader.ReadVarUhShort();
            m_nbConnectedMembers = reader.ReadVarUhShort();
        }
    }
}
