//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Guild
{
    using System.Collections.Generic;
    using System;
    
    
    public class GuildInvitationAnswerMessage : NetworkMessage
    {
        
        public const int Id = 5556;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private bool m_accept;
        
        public virtual bool Accept
        {
            get
            {
                return m_accept;
            }
            set
            {
                m_accept = value;
            }
        }
        
        public void Initiate(bool accept)
        {
            m_accept = accept;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteBoolean(m_accept);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_accept = reader.ReadBoolean();
        }
    }
}
