//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Interactive
{
    using System.Collections.Generic;
    using System;
    
    
    public class InteractiveElementNamedSkill : InteractiveElementSkill
    {
        
        public const int Id = 220;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private uint m_nameId;
        
        public virtual uint NameId
        {
            get
            {
                return m_nameId;
            }
            set
            {
                m_nameId = value;
            }
        }
        
        public void Initiate(uint nameId)
        {
            m_nameId = nameId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhInt(m_nameId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_nameId = reader.ReadVarUhInt();
        }
    }
}
