//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Interactive
{
    using System.Collections.Generic;
    using System;
    
    
    public class InteractiveElementWithAgeBonus : InteractiveElement
    {
        
        public const int Id = 398;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private short m_ageBonus;
        
        public virtual short AgeBonus
        {
            get
            {
                return m_ageBonus;
            }
            set
            {
                m_ageBonus = value;
            }
        }
        
        public void Initiate(short ageBonus)
        {
            m_ageBonus = ageBonus;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort(m_ageBonus);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_ageBonus = reader.ReadShort();
        }
    }
}
