//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Interactive
{
    using System.Collections.Generic;
    using System;
    
    
    public class MapObstacle : NetworkType
    {
        
        public const int Id = 200;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_obstacleCellId;
        
        public virtual ushort ObstacleCellId
        {
            get
            {
                return m_obstacleCellId;
            }
            set
            {
                m_obstacleCellId = value;
            }
        }
        
        private byte m_state;
        
        public virtual byte State
        {
            get
            {
                return m_state;
            }
            set
            {
                m_state = value;
            }
        }
        
        public void Initiate(ushort obstacleCellId, byte state)
        {
            m_obstacleCellId = obstacleCellId;
            m_state = state;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhShort(m_obstacleCellId);
            writer.WriteByte(m_state);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_obstacleCellId = reader.ReadVarUhShort();
            m_state = reader.ReadByte();
        }
    }
}
