//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Friend
{
    using System.Collections.Generic;
    using System;
    
    
    public class FriendInformations : AbstractContactInformations
    {
        
        public const int Id = 78;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private byte m_playerState;
        
        public virtual byte PlayerState
        {
            get
            {
                return m_playerState;
            }
            set
            {
                m_playerState = value;
            }
        }
        
        private ushort m_lastConnection;
        
        public virtual ushort LastConnection
        {
            get
            {
                return m_lastConnection;
            }
            set
            {
                m_lastConnection = value;
            }
        }
        
        private int m_achievementPoints;
        
        public virtual int AchievementPoints
        {
            get
            {
                return m_achievementPoints;
            }
            set
            {
                m_achievementPoints = value;
            }
        }
        
        public void Initiate(byte playerState, ushort lastConnection, int achievementPoints)
        {
            m_playerState = playerState;
            m_lastConnection = lastConnection;
            m_achievementPoints = achievementPoints;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteByte(m_playerState);
            writer.WriteVarUhShort(m_lastConnection);
            writer.WriteInt(m_achievementPoints);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_playerState = reader.ReadByte();
            m_lastConnection = reader.ReadVarUhShort();
            m_achievementPoints = reader.ReadInt();
        }
    }
}
