//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Friend
{
    using Common.Protocol.Network.Enums;
    using System.Collections.Generic;
    using System;
    
    
    public class IgnoredOnlineInformations : IgnoredInformations
    {
        
        public const int Id = 105;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private uint m_playerId;
        
        public virtual uint PlayerId
        {
            get
            {
                return m_playerId;
            }
            set
            {
                m_playerId = value;
            }
        }
        
        private string m_playerName;
        
        public virtual string PlayerName
        {
            get
            {
                return m_playerName;
            }
            set
            {
                m_playerName = value;
            }
        }
        
        private byte m_breed;
        
        public virtual byte Breed
        {
            get
            {
                return m_breed;
            }
            set
            {
                m_breed = value;
            }
        }
        
        private bool m_sex;
        
        public virtual bool Sex
        {
            get
            {
                return m_sex;
            }
            set
            {
                m_sex = value;
            }
        }
        
        public void Initiate(uint playerId, string playerName, byte breed, bool sex)
        {
            m_playerId = playerId;
            m_playerName = playerName;
            m_breed = breed;
            m_sex = sex;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhInt(m_playerId);
            writer.WriteUTF(m_playerName);
            writer.WriteByte(m_breed);
            writer.WriteBoolean(m_sex);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_playerId = reader.ReadVarUhInt();
            m_playerName = reader.ReadUTF();
            m_breed = reader.ReadByte();
            m_sex = reader.ReadBoolean();
        }
    }
}
