//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Shortcut
{
    using Common.Protocol.Network.Types.Game.Shortcut;
    using Common.Protocol.Network;
    using System.Collections.Generic;
    using System;
    
    
    public class ShortcutBarContentMessage : NetworkMessage
    {
        
        public const int Id = 6231;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private byte m_barType;
        
        public virtual byte BarType
        {
            get
            {
                return m_barType;
            }
            set
            {
                m_barType = value;
            }
        }
        
        private List<Shortcut> m_shortcuts;
        
        public virtual List<Shortcut> Shortcuts
        {
            get
            {
                return m_shortcuts;
            }
            set
            {
                m_shortcuts = value;
            }
        }
        
        public void Initiate(byte barType, List<Shortcut> shortcuts)
        {
            m_barType = barType;
            m_shortcuts = shortcuts;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteByte(m_barType);
            writer.WriteShort(((short)(m_shortcuts.Count)));
            int shortcutsIndex;
            for (shortcutsIndex = 0; (shortcutsIndex < m_shortcuts.Count); shortcutsIndex = (shortcutsIndex + 1))
            {
                Shortcut objectToSend = m_shortcuts[shortcutsIndex];
                writer.WriteUShort(((ushort)(objectToSend.ProtocolId)));
                objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_barType = reader.ReadByte();
            int shortcutsCount = reader.ReadUShort();
            int shortcutsIndex;
            m_shortcuts = new System.Collections.Generic.List<Shortcut>();
            for (shortcutsIndex = 0; (shortcutsIndex < shortcutsCount); shortcutsIndex = (shortcutsIndex + 1))
            {
                Shortcut objectToAdd = ProtocolManager.GetTypeInstance<Shortcut>(reader.ReadUShort());
                objectToAdd.Deserialize(reader);
                m_shortcuts.Add(objectToAdd);
            }
        }
    }
}
