//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Roleplay.Houses.Guild
{
    using System.Collections.Generic;
    using System;
    
    
    public class HouseGuildShareRequestMessage : NetworkMessage
    {
        
        public const int Id = 5704;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private bool m_enable;
        
        public virtual bool Enable
        {
            get
            {
                return m_enable;
            }
            set
            {
                m_enable = value;
            }
        }
        
        private uint m_rights;
        
        public virtual uint Rights
        {
            get
            {
                return m_rights;
            }
            set
            {
                m_rights = value;
            }
        }
        
        public void Initiate(bool enable, uint rights)
        {
            m_enable = enable;
            m_rights = rights;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteBoolean(m_enable);
            writer.WriteVarUhInt(m_rights);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_enable = reader.ReadBoolean();
            m_rights = reader.ReadVarUhInt();
        }
    }
}
