//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Roleplay.Npc
{
    using System.Collections.Generic;
    using System;
    
    
    public class NpcDialogReplyMessage : NetworkMessage
    {
        
        public const int Id = 5616;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_replyId;
        
        public virtual ushort ReplyId
        {
            get
            {
                return m_replyId;
            }
            set
            {
                m_replyId = value;
            }
        }
        
        public void Initiate(ushort replyId)
        {
            m_replyId = replyId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhShort(m_replyId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_replyId = reader.ReadVarUhShort();
        }
    }
}
