//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Roleplay.Npc
{
    using Common.Protocol.Network.Types.Game.Context.Roleplay;
    using System.Collections.Generic;
    using System;
    
    
    public class TaxCollectorDialogQuestionBasicMessage : NetworkMessage
    {
        
        public const int Id = 5619;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private BasicGuildInformations m_guildInfo;
        
        public virtual BasicGuildInformations GuildInfo
        {
            get
            {
                return m_guildInfo;
            }
            set
            {
                m_guildInfo = value;
            }
        }
        
        public void Initiate(BasicGuildInformations guildInfo)
        {
            m_guildInfo = guildInfo;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            m_guildInfo.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_guildInfo = new BasicGuildInformations();
            m_guildInfo.Deserialize(reader);
        }
    }
}
