//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Mount
{
    using System.Collections.Generic;
    using System;
    
    
    public class MountRidingMessage : NetworkMessage
    {
        
        public const int Id = 5967;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private bool m_isRiding;
        
        public virtual bool IsRiding
        {
            get
            {
                return m_isRiding;
            }
            set
            {
                m_isRiding = value;
            }
        }
        
        public void Initiate(bool isRiding)
        {
            m_isRiding = isRiding;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteBoolean(m_isRiding);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_isRiding = reader.ReadBoolean();
        }
    }
}
