//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Mount
{
    using System.Collections.Generic;
    using System;
    
    
    public class PaddockMoveItemRequestMessage : NetworkMessage
    {
        
        public const int Id = 6052;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_oldCellId;
        
        public virtual ushort OldCellId
        {
            get
            {
                return m_oldCellId;
            }
            set
            {
                m_oldCellId = value;
            }
        }
        
        private ushort m_newCellId;
        
        public virtual ushort NewCellId
        {
            get
            {
                return m_newCellId;
            }
            set
            {
                m_newCellId = value;
            }
        }
        
        public void Initiate(ushort oldCellId, ushort newCellId)
        {
            m_oldCellId = oldCellId;
            m_newCellId = newCellId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhShort(m_oldCellId);
            writer.WriteVarUhShort(m_newCellId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_oldCellId = reader.ReadVarUhShort();
            m_newCellId = reader.ReadVarUhShort();
        }
    }
}
