//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Mount
{
    using System.Collections.Generic;
    using System;
    
    
    public class PaddockBuyResultMessage : NetworkMessage
    {
        
        public const int Id = 6516;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private int m_paddockId;
        
        public virtual int PaddockId
        {
            get
            {
                return m_paddockId;
            }
            set
            {
                m_paddockId = value;
            }
        }
        
        private bool m_bought;
        
        public virtual bool Bought
        {
            get
            {
                return m_bought;
            }
            set
            {
                m_bought = value;
            }
        }
        
        private uint m_realPrice;
        
        public virtual uint RealPrice
        {
            get
            {
                return m_realPrice;
            }
            set
            {
                m_realPrice = value;
            }
        }
        
        public void Initiate(int paddockId, bool bought, uint realPrice)
        {
            m_paddockId = paddockId;
            m_bought = bought;
            m_realPrice = realPrice;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteInt(m_paddockId);
            writer.WriteBoolean(m_bought);
            writer.WriteVarUhInt(m_realPrice);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_paddockId = reader.ReadInt();
            m_bought = reader.ReadBoolean();
            m_realPrice = reader.ReadVarUhInt();
        }
    }
}
