//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Context.Fight
{
    using Common.Protocol.Network;
    using System.Collections.Generic;
    using System;
    
    
    public class FightResultPlayerListEntry : FightResultFighterListEntry
    {
        
        public const int Id = 24;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private sbyte m_level;
        
        public virtual sbyte Level
        {
            get
            {
                return m_level;
            }
            set
            {
                m_level = value;
            }
        }
        
        private List<FightResultAdditionalData> m_additional;
        
        public virtual List<FightResultAdditionalData> Additional
        {
            get
            {
                return m_additional;
            }
            set
            {
                m_additional = value;
            }
        }
        
        public void Initiate(sbyte level, List<FightResultAdditionalData> additional)
        {
            m_level = level;
            m_additional = additional;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteSByte(m_level);
            writer.WriteShort(((short)(m_additional.Count)));
            int additionalIndex;
            for (additionalIndex = 0; (additionalIndex < m_additional.Count); additionalIndex = (additionalIndex + 1))
            {
                FightResultAdditionalData objectToSend = m_additional[additionalIndex];
                writer.WriteUShort(((ushort)(objectToSend.ProtocolId)));
                objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_level = reader.ReadSByte();
            int additionalCount = reader.ReadUShort();
            int additionalIndex;
            m_additional = new System.Collections.Generic.List<FightResultAdditionalData>();
            for (additionalIndex = 0; (additionalIndex < additionalCount); additionalIndex = (additionalIndex + 1))
            {
                FightResultAdditionalData objectToAdd = ProtocolManager.GetTypeInstance<FightResultAdditionalData>(reader.ReadUShort());
                objectToAdd.Deserialize(reader);
                m_additional.Add(objectToAdd);
            }
        }
    }
}
