//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Context.Fight
{
    using System.Collections.Generic;
    using System;
    
    
    public class FightResultFighterListEntry : FightResultListEntry
    {
        
        public const int Id = 189;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private int m_ObjectId;
        
        public virtual int ObjectId
        {
            get
            {
                return m_ObjectId;
            }
            set
            {
                m_ObjectId = value;
            }
        }
        
        private bool m_alive;
        
        public virtual bool Alive
        {
            get
            {
                return m_alive;
            }
            set
            {
                m_alive = value;
            }
        }
        
        public void Initiate(int objectId, bool alive)
        {
            m_ObjectId = objectId;
            m_alive = alive;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteInt(m_ObjectId);
            writer.WriteBoolean(m_alive);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_ObjectId = reader.ReadInt();
            m_alive = reader.ReadBoolean();
        }
    }
}
