//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Context.Fight
{
    using Common.Protocol.Network.Types.Game.Context.Roleplay;
    using System.Collections.Generic;
    using System;
    
    
    public class FightResultTaxCollectorListEntry : FightResultFighterListEntry
    {
        
        public const int Id = 84;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private sbyte m_level;
        
        public virtual sbyte Level
        {
            get
            {
                return m_level;
            }
            set
            {
                m_level = value;
            }
        }
        
        private BasicGuildInformations m_guildInfo;
        
        public virtual BasicGuildInformations GuildInfo
        {
            get
            {
                return m_guildInfo;
            }
            set
            {
                m_guildInfo = value;
            }
        }
        
        private int m_experienceForGuild;
        
        public virtual int ExperienceForGuild
        {
            get
            {
                return m_experienceForGuild;
            }
            set
            {
                m_experienceForGuild = value;
            }
        }
        
        public void Initiate(sbyte level, BasicGuildInformations guildInfo, int experienceForGuild)
        {
            m_level = level;
            m_guildInfo = guildInfo;
            m_experienceForGuild = experienceForGuild;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteSByte(m_level);
            m_guildInfo.Serialize(writer);
            writer.WriteInt(m_experienceForGuild);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_level = reader.ReadSByte();
            m_guildInfo = new BasicGuildInformations();
            m_guildInfo.Deserialize(reader);
            m_experienceForGuild = reader.ReadInt();
        }
    }
}
