//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Context.Fight
{
    using Common.Protocol.Network.Types.Game.Look;
    using Common.Protocol.Network.Types.Game.Context;
    using System.Collections.Generic;
    using System;
    
    
    public class GameFightAIInformations : GameFightFighterInformations
    {
        
        public const int Id = 151;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        public void Initiate()
        {
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
        }
    }
}
