//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Context.Fight
{
    using System.Collections.Generic;
    using System;
    
    
    public class GameFightSpellCooldown : NetworkType
    {
        
        public const int Id = 205;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private int m_spellId;
        
        public virtual int SpellId
        {
            get
            {
                return m_spellId;
            }
            set
            {
                m_spellId = value;
            }
        }
        
        private byte m_cooldown;
        
        public virtual byte Cooldown
        {
            get
            {
                return m_cooldown;
            }
            set
            {
                m_cooldown = value;
            }
        }
        
        public void Initiate(int spellId, byte cooldown)
        {
            m_spellId = spellId;
            m_cooldown = cooldown;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteInt(m_spellId);
            writer.WriteByte(m_cooldown);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_spellId = reader.ReadInt();
            m_cooldown = reader.ReadByte();
        }
    }
}
