//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Context.Fight
{
    using Common.Protocol.Network.Types.Game.Look;
    using Common.Protocol.Network.Types.Game.Context;
    using System.Collections.Generic;
    using System;
    
    
    public class GameFightMonsterInformations : GameFightAIInformations
    {
        
        public const int Id = 29;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_creatureGenericId;
        
        public virtual ushort CreatureGenericId
        {
            get
            {
                return m_creatureGenericId;
            }
            set
            {
                m_creatureGenericId = value;
            }
        }
        
        private byte m_creatureGrade;
        
        public virtual byte CreatureGrade
        {
            get
            {
                return m_creatureGrade;
            }
            set
            {
                m_creatureGrade = value;
            }
        }
        
        public void Initiate(ushort creatureGenericId, byte creatureGrade)
        {
            m_creatureGenericId = creatureGenericId;
            m_creatureGrade = creatureGrade;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhShort(m_creatureGenericId);
            writer.WriteByte(m_creatureGrade);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_creatureGenericId = reader.ReadVarUhShort();
            m_creatureGrade = reader.ReadByte();
        }
    }
}
