//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Character.Stats
{
    using Common.Protocol.Network.Types.Game.Character.Characteristic;
    using System.Collections.Generic;
    using System;
    
    
    public class CharacterStatsListMessage : NetworkMessage
    {
        
        public const int Id = 500;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private CharacterCharacteristicsInformations m_stats;
        
        public virtual CharacterCharacteristicsInformations Stats
        {
            get
            {
                return m_stats;
            }
            set
            {
                m_stats = value;
            }
        }
        
        public void Initiate(CharacterCharacteristicsInformations stats)
        {
            m_stats = stats;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            m_stats.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_stats = new CharacterCharacteristicsInformations();
            m_stats.Deserialize(reader);
        }
    }
}
