//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Friend
{
    using System.Collections.Generic;
    using System;
    
    
    public class FriendDeleteResultMessage : NetworkMessage
    {
        
        public const int Id = 5601;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private bool m_success;
        
        public virtual bool Success
        {
            get
            {
                return m_success;
            }
            set
            {
                m_success = value;
            }
        }
        
        private string m_name;
        
        public virtual string Name
        {
            get
            {
                return m_name;
            }
            set
            {
                m_name = value;
            }
        }
        
        public void Initiate(bool success, string name)
        {
            m_success = success;
            m_name = name;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteBoolean(m_success);
            writer.WriteUTF(m_name);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_success = reader.ReadBoolean();
            m_name = reader.ReadUTF();
        }
    }
}
