//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Friend
{
    using Common.Protocol.Network.Types.Game.Friend;
    using Common.Protocol.Network;
    using System.Collections.Generic;
    using System;
    
    
    public class FriendUpdateMessage : NetworkMessage
    {
        
        public const int Id = 5924;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private FriendInformations m_friendUpdated;
        
        public virtual FriendInformations FriendUpdated
        {
            get
            {
                return m_friendUpdated;
            }
            set
            {
                m_friendUpdated = value;
            }
        }
        
        public void Initiate(FriendInformations friendUpdated)
        {
            m_friendUpdated = friendUpdated;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteUShort(((ushort)(m_friendUpdated.ProtocolId)));
            m_friendUpdated.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_friendUpdated = ProtocolManager.GetTypeInstance<FriendInformations>(reader.ReadUShort());
            m_friendUpdated.Deserialize(reader);
        }
    }
}
