//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Friend
{
    using System.Collections.Generic;
    using System;
    
    
    public class IgnoredDeleteRequestMessage : NetworkMessage
    {
        
        public const int Id = 5680;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private int m_accountId;
        
        public virtual int AccountId
        {
            get
            {
                return m_accountId;
            }
            set
            {
                m_accountId = value;
            }
        }
        
        private bool m_session;
        
        public virtual bool Session
        {
            get
            {
                return m_session;
            }
            set
            {
                m_session = value;
            }
        }
        
        public void Initiate(int accountId, bool session)
        {
            m_accountId = accountId;
            m_session = session;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteInt(m_accountId);
            writer.WriteBoolean(m_session);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_accountId = reader.ReadInt();
            m_session = reader.ReadBoolean();
        }
    }
}
