//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Friend
{
    using Common.Protocol.Network.Types.Game.Friend;
    using Common.Protocol.Network;
    using System.Collections.Generic;
    using System;
    
    
    public class SpouseInformationsMessage : NetworkMessage
    {
        
        public const int Id = 6356;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private FriendSpouseInformations m_spouse;
        
        public virtual FriendSpouseInformations Spouse
        {
            get
            {
                return m_spouse;
            }
            set
            {
                m_spouse = value;
            }
        }
        
        public void Initiate(FriendSpouseInformations spouse)
        {
            m_spouse = spouse;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteUShort(((ushort)(m_spouse.ProtocolId)));
            m_spouse.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_spouse = ProtocolManager.GetTypeInstance<FriendSpouseInformations>(reader.ReadUShort());
            m_spouse.Deserialize(reader);
        }
    }
}
