//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Character.Deletion
{
    using System.Collections.Generic;
    using System;
    
    
    public class CharacterDeletionRequestMessage : NetworkMessage
    {
        
        public const int Id = 165;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private int m_characterId;
        
        public virtual int CharacterId
        {
            get
            {
                return m_characterId;
            }
            set
            {
                m_characterId = value;
            }
        }
        
        private string m_secretAnswerHash;
        
        public virtual string SecretAnswerHash
        {
            get
            {
                return m_secretAnswerHash;
            }
            set
            {
                m_secretAnswerHash = value;
            }
        }
        
        public void Initiate(int characterId, string secretAnswerHash)
        {
            m_characterId = characterId;
            m_secretAnswerHash = secretAnswerHash;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteInt(m_characterId);
            writer.WriteUTF(m_secretAnswerHash);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_characterId = reader.ReadInt();
            m_secretAnswerHash = reader.ReadUTF();
        }
    }
}
