//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Idol
{
    using Common.Protocol.Network.Types.Game.Idol;
    using Common.Protocol.Network;
    using System.Collections.Generic;
    using System;
    
    
    public class IdolFightPreparationUpdateMessage : NetworkMessage
    {
        
        public const int Id = 6586;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private byte m_idolSource;
        
        public virtual byte IdolSource
        {
            get
            {
                return m_idolSource;
            }
            set
            {
                m_idolSource = value;
            }
        }
        
        private List<Idol> m_idols;
        
        public virtual List<Idol> Idols
        {
            get
            {
                return m_idols;
            }
            set
            {
                m_idols = value;
            }
        }
        
        public void Initiate(byte idolSource, List<Idol> idols)
        {
            m_idolSource = idolSource;
            m_idols = idols;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteByte(m_idolSource);
            writer.WriteShort(((short)(m_idols.Count)));
            int idolsIndex;
            for (idolsIndex = 0; (idolsIndex < m_idols.Count); idolsIndex = (idolsIndex + 1))
            {
                Idol objectToSend = m_idols[idolsIndex];
                writer.WriteUShort(((ushort)(objectToSend.ProtocolId)));
                objectToSend.Serialize(writer);
            }
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_idolSource = reader.ReadByte();
            int idolsCount = reader.ReadUShort();
            int idolsIndex;
            m_idols = new System.Collections.Generic.List<Idol>();
            for (idolsIndex = 0; (idolsIndex < idolsCount); idolsIndex = (idolsIndex + 1))
            {
                Idol objectToAdd = ProtocolManager.GetTypeInstance<Idol>(reader.ReadUShort());
                objectToAdd.Deserialize(reader);
                m_idols.Add(objectToAdd);
            }
        }
    }
}
