//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Context.Roleplay.Job
{
    using System.Collections.Generic;
    using System;
    
    
    public class JobCrafterDirectoryListEntry : NetworkType
    {
        
        public const int Id = 196;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private JobCrafterDirectoryEntryPlayerInfo m_playerInfo;
        
        public virtual JobCrafterDirectoryEntryPlayerInfo PlayerInfo
        {
            get
            {
                return m_playerInfo;
            }
            set
            {
                m_playerInfo = value;
            }
        }
        
        private JobCrafterDirectoryEntryJobInfo m_jobInfo;
        
        public virtual JobCrafterDirectoryEntryJobInfo JobInfo
        {
            get
            {
                return m_jobInfo;
            }
            set
            {
                m_jobInfo = value;
            }
        }
        
        public void Initiate(JobCrafterDirectoryEntryPlayerInfo playerInfo, JobCrafterDirectoryEntryJobInfo jobInfo)
        {
            m_playerInfo = playerInfo;
            m_jobInfo = jobInfo;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            m_playerInfo.Serialize(writer);
            m_jobInfo.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_playerInfo = new JobCrafterDirectoryEntryPlayerInfo();
            m_playerInfo.Deserialize(reader);
            m_jobInfo = new JobCrafterDirectoryEntryJobInfo();
            m_jobInfo.Deserialize(reader);
        }
    }
}
