//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Security
{
    using System.Collections.Generic;
    using System;
    
    
    public class CheckIntegrityMessage : NetworkMessage
    {
        
        public const int Id = 6372;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private List<System.Byte> m_data;
        
        public virtual List<System.Byte> Data
        {
            get
            {
                return m_data;
            }
            set
            {
                m_data = value;
            }
        }
        
        public void Initiate(List<System.Byte> data)
        {
            m_data = data;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteShort(((short)(m_data.Count)));
            int dataIndex;
            for (dataIndex = 0; (dataIndex < m_data.Count); dataIndex = (dataIndex + 1))
            {
                writer.WriteByte(m_data[dataIndex]);
            }
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            int dataCount = reader.ReadUShort();
            int dataIndex;
            m_data = new System.Collections.Generic.List<byte>();
            for (dataIndex = 0; (dataIndex < dataCount); dataIndex = (dataIndex + 1))
            {
                m_data.Add(reader.ReadByte());
            }
        }
    }
}
