//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Basic
{
    using System.Collections.Generic;
    using System;
    
    
    public class BasicWhoAmIRequestMessage : NetworkMessage
    {
        
        public const int Id = 5664;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private bool m_verbose;
        
        public virtual bool Verbose
        {
            get
            {
                return m_verbose;
            }
            set
            {
                m_verbose = value;
            }
        }
        
        public void Initiate(bool verbose)
        {
            m_verbose = verbose;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteBoolean(m_verbose);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_verbose = reader.ReadBoolean();
        }
    }
}
