//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Basic
{
    using System.Collections.Generic;
    using System;
    
    
    public class SequenceNumberMessage : NetworkMessage
    {
        
        public const int Id = 6317;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_number;
        
        public virtual ushort Number
        {
            get
            {
                return m_number;
            }
            set
            {
                m_number = value;
            }
        }
        
        public void Initiate(ushort number)
        {
            m_number = number;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteUShort(m_number);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_number = reader.ReadUShort();
        }
    }
}
