//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context
{
    using System.Collections.Generic;
    using System;
    
    
    public class GameContextRemoveMultipleElementsWithEventsMessage : GameContextRemoveMultipleElementsMessage
    {
        
        public const int Id = 6416;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private List<System.Byte> m_elementEventIds;
        
        public virtual List<System.Byte> ElementEventIds
        {
            get
            {
                return m_elementEventIds;
            }
            set
            {
                m_elementEventIds = value;
            }
        }
        
        public void Initiate(List<System.Byte> elementEventIds)
        {
            m_elementEventIds = elementEventIds;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort(((short)(m_elementEventIds.Count)));
            int elementEventIdsIndex;
            for (elementEventIdsIndex = 0; (elementEventIdsIndex < m_elementEventIds.Count); elementEventIdsIndex = (elementEventIdsIndex + 1))
            {
                writer.WriteByte(m_elementEventIds[elementEventIdsIndex]);
            }
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            int elementEventIdsCount = reader.ReadUShort();
            int elementEventIdsIndex;
            m_elementEventIds = new System.Collections.Generic.List<byte>();
            for (elementEventIdsIndex = 0; (elementEventIdsIndex < elementEventIdsCount); elementEventIdsIndex = (elementEventIdsIndex + 1))
            {
                m_elementEventIds.Add(reader.ReadByte());
            }
        }
    }
}
