//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Roleplay.Fight
{
    using System.Collections.Generic;
    using System;
    
    
    public class GameRolePlayAttackMonsterRequestMessage : NetworkMessage
    {
        
        public const int Id = 6191;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private int m_monsterGroupId;
        
        public virtual int MonsterGroupId
        {
            get
            {
                return m_monsterGroupId;
            }
            set
            {
                m_monsterGroupId = value;
            }
        }
        
        public void Initiate(int monsterGroupId)
        {
            m_monsterGroupId = monsterGroupId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteInt(m_monsterGroupId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_monsterGroupId = reader.ReadInt();
        }
    }
}
