//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Enums
{
    
    
    public enum PrismListenEnum
    {
        
        PRISM_LISTEN_NONE = 0,
        
        PRISM_LISTEN_MINE = 1,
        
        PRISM_LISTEN_ALL = 2,
    }
}
