//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Enums
{
    
    
    public enum TaxCollectorStateEnum
    {
        
        STATE_COLLECTING = 0,
        
        STATE_WAITING_FOR_HELP = 1,
        
        STATE_FIGHTING = 2,
    }
}
