//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Roleplay.Objects
{
    using System.Collections.Generic;
    using System;
    
    
    public class ObjectGroundRemovedMultipleMessage : NetworkMessage
    {
        
        public const int Id = 5944;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private List<System.UInt16> m_cells;
        
        public virtual List<System.UInt16> Cells
        {
            get
            {
                return m_cells;
            }
            set
            {
                m_cells = value;
            }
        }
        
        public void Initiate(List<System.UInt16> cells)
        {
            m_cells = cells;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteShort(((short)(m_cells.Count)));
            int cellsIndex;
            for (cellsIndex = 0; (cellsIndex < m_cells.Count); cellsIndex = (cellsIndex + 1))
            {
                writer.WriteVarUhShort(m_cells[cellsIndex]);
            }
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            int cellsCount = reader.ReadUShort();
            int cellsIndex;
            m_cells = new System.Collections.Generic.List<ushort>();
            for (cellsIndex = 0; (cellsIndex < cellsCount); cellsIndex = (cellsIndex + 1))
            {
                m_cells.Add(reader.ReadVarUhShort());
            }
        }
    }
}
