//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Context.Roleplay
{
    using Common.Protocol.Network.Types.Game.Guild;
    using System.Collections.Generic;
    using System;
    
    
    public class AllianceInformations : BasicNamedAllianceInformations
    {
        
        public const int Id = 417;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private GuildEmblem m_allianceEmblem;
        
        public virtual GuildEmblem AllianceEmblem
        {
            get
            {
                return m_allianceEmblem;
            }
            set
            {
                m_allianceEmblem = value;
            }
        }
        
        public void Initiate(GuildEmblem allianceEmblem)
        {
            m_allianceEmblem = allianceEmblem;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            m_allianceEmblem.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_allianceEmblem = new GuildEmblem();
            m_allianceEmblem.Deserialize(reader);
        }
    }
}
