//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Context.Roleplay
{
    using Common.Protocol.Network.Types.Game.Look;
    using Common.Protocol.Network.Types.Game.Context;
    using Common.Protocol.Network;
    using System.Collections.Generic;
    using System;
    
    
    public class GameRolePlayHumanoidInformations : GameRolePlayNamedActorInformations
    {
        
        public const int Id = 159;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private HumanInformations m_humanoidInfo;
        
        public virtual HumanInformations HumanoidInfo
        {
            get
            {
                return m_humanoidInfo;
            }
            set
            {
                m_humanoidInfo = value;
            }
        }
        
        private int m_accountId;
        
        public virtual int AccountId
        {
            get
            {
                return m_accountId;
            }
            set
            {
                m_accountId = value;
            }
        }
        
        public void Initiate(HumanInformations humanoidInfo, int accountId)
        {
            m_humanoidInfo = humanoidInfo;
            m_accountId = accountId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteUShort(((ushort)(m_humanoidInfo.ProtocolId)));
            m_humanoidInfo.Serialize(writer);
            writer.WriteInt(m_accountId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_humanoidInfo = ProtocolManager.GetTypeInstance<HumanInformations>(reader.ReadUShort());
            m_humanoidInfo.Deserialize(reader);
            m_accountId = reader.ReadInt();
        }
    }
}
