//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Context.Roleplay
{
    using Common.Protocol.Network.Types.Game.Look;
    using Common.Protocol.Network.Types.Game.Context;
    using System.Collections.Generic;
    using System;
    
    
    public class GameRolePlayMutantInformations : GameRolePlayHumanoidInformations
    {
        
        public const int Id = 3;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_monsterId;
        
        public virtual ushort MonsterId
        {
            get
            {
                return m_monsterId;
            }
            set
            {
                m_monsterId = value;
            }
        }
        
        private byte m_powerLevel;
        
        public virtual byte PowerLevel
        {
            get
            {
                return m_powerLevel;
            }
            set
            {
                m_powerLevel = value;
            }
        }
        
        public void Initiate(ushort monsterId, byte powerLevel)
        {
            m_monsterId = monsterId;
            m_powerLevel = powerLevel;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhShort(m_monsterId);
            writer.WriteByte(m_powerLevel);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_monsterId = reader.ReadVarUhShort();
            m_powerLevel = reader.ReadByte();
        }
    }
}
