//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Context.Roleplay
{
    using Common.Protocol.Network.Types.Game.Guild;
    using System.Collections.Generic;
    using System;
    
    
    public class GuildInAllianceInformations : GuildInformations
    {
        
        public const int Id = 420;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private sbyte m_guildLevel;
        
        public virtual sbyte GuildLevel
        {
            get
            {
                return m_guildLevel;
            }
            set
            {
                m_guildLevel = value;
            }
        }
        
        private sbyte m_nbMembers;
        
        public virtual sbyte NbMembers
        {
            get
            {
                return m_nbMembers;
            }
            set
            {
                m_nbMembers = value;
            }
        }
        
        private bool m_enabled;
        
        public virtual bool Enabled
        {
            get
            {
                return m_enabled;
            }
            set
            {
                m_enabled = value;
            }
        }
        
        public void Initiate(sbyte guildLevel, sbyte nbMembers, bool enabled)
        {
            m_guildLevel = guildLevel;
            m_nbMembers = nbMembers;
            m_enabled = enabled;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteSByte(m_guildLevel);
            writer.WriteSByte(m_nbMembers);
            writer.WriteBoolean(m_enabled);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_guildLevel = reader.ReadSByte();
            m_nbMembers = reader.ReadSByte();
            m_enabled = reader.ReadBoolean();
        }
    }
}
