//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Context.Roleplay
{
    using System.Collections.Generic;
    using System;
    
    
    public class HumanOptionGuild : HumanOption
    {
        
        public const int Id = 409;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private GuildInformations m_guildInformations;
        
        public virtual GuildInformations GuildInformations
        {
            get
            {
                return m_guildInformations;
            }
            set
            {
                m_guildInformations = value;
            }
        }
        
        public void Initiate(GuildInformations guildInformations)
        {
            m_guildInformations = guildInformations;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            m_guildInformations.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_guildInformations = new GuildInformations();
            m_guildInformations.Deserialize(reader);
        }
    }
}
