//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Context.Roleplay
{
    using System.Collections.Generic;
    using System;
    
    
    public class HumanOptionOrnament : HumanOption
    {
        
        public const int Id = 411;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_ornamentId;
        
        public virtual ushort OrnamentId
        {
            get
            {
                return m_ornamentId;
            }
            set
            {
                m_ornamentId = value;
            }
        }
        
        public void Initiate(ushort ornamentId)
        {
            m_ornamentId = ornamentId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhShort(m_ornamentId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_ornamentId = reader.ReadVarUhShort();
        }
    }
}
