//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Context.Roleplay
{
    using Common.Protocol.Network.Types.Game.Look;
    using System.Collections.Generic;
    using System;
    
    
    public class MonsterInGroupInformations : MonsterInGroupLightInformations
    {
        
        public const int Id = 144;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private EntityLook m_look;
        
        public virtual EntityLook Look
        {
            get
            {
                return m_look;
            }
            set
            {
                m_look = value;
            }
        }
        
        public void Initiate(EntityLook look)
        {
            m_look = look;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            m_look.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_look = new EntityLook();
            m_look.Deserialize(reader);
        }
    }
}
