//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Actions.Fight
{
    using System.Collections.Generic;
    using System;
    
    
    public class FightTemporarySpellBoostEffect : FightTemporaryBoostEffect
    {
        
        public const int Id = 207;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_boostedSpellId;
        
        public virtual ushort BoostedSpellId
        {
            get
            {
                return m_boostedSpellId;
            }
            set
            {
                m_boostedSpellId = value;
            }
        }
        
        public void Initiate(ushort boostedSpellId)
        {
            m_boostedSpellId = boostedSpellId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhShort(m_boostedSpellId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_boostedSpellId = reader.ReadVarUhShort();
        }
    }
}
