//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Actions.Fight
{
    using System.Collections.Generic;
    using System;
    
    
    public class FightTemporarySpellImmunityEffect : AbstractFightDispellableEffect
    {
        
        public const int Id = 366;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private int m_immuneSpellId;
        
        public virtual int ImmuneSpellId
        {
            get
            {
                return m_immuneSpellId;
            }
            set
            {
                m_immuneSpellId = value;
            }
        }
        
        public void Initiate(int immuneSpellId)
        {
            m_immuneSpellId = immuneSpellId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteInt(m_immuneSpellId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_immuneSpellId = reader.ReadInt();
        }
    }
}
