//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Mount
{
    using System.Collections.Generic;
    using System;
    
    
    public class ItemDurability : NetworkType
    {
        
        public const int Id = 168;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private short m_durability;
        
        public virtual short Durability
        {
            get
            {
                return m_durability;
            }
            set
            {
                m_durability = value;
            }
        }
        
        private short m_durabilityMax;
        
        public virtual short DurabilityMax
        {
            get
            {
                return m_durabilityMax;
            }
            set
            {
                m_durabilityMax = value;
            }
        }
        
        public void Initiate(short durability, short durabilityMax)
        {
            m_durability = durability;
            m_durabilityMax = durabilityMax;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteShort(m_durability);
            writer.WriteShort(m_durabilityMax);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_durability = reader.ReadShort();
            m_durabilityMax = reader.ReadShort();
        }
    }
}
