//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Connection
{
    using System.Collections.Generic;
    using System;
    
    
    public class IdentificationFailedBannedMessage : IdentificationFailedMessage
    {
        
        public const int Id = 6174;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private double m_banEndDate;
        
        public virtual double BanEndDate
        {
            get
            {
                return m_banEndDate;
            }
            set
            {
                m_banEndDate = value;
            }
        }
        
        public void Initiate(double banEndDate)
        {
            m_banEndDate = banEndDate;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteDouble(m_banEndDate);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_banEndDate = reader.ReadDouble();
        }
    }
}
