//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Roleplay.Quest
{
    using System.Collections.Generic;
    using System;
    
    
    public class QuestObjectiveValidationMessage : NetworkMessage
    {
        
        public const int Id = 6085;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_questId;
        
        public virtual ushort QuestId
        {
            get
            {
                return m_questId;
            }
            set
            {
                m_questId = value;
            }
        }
        
        private ushort m_objectiveId;
        
        public virtual ushort ObjectiveId
        {
            get
            {
                return m_objectiveId;
            }
            set
            {
                m_objectiveId = value;
            }
        }
        
        public void Initiate(ushort questId, ushort objectiveId)
        {
            m_questId = questId;
            m_objectiveId = objectiveId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhShort(m_questId);
            writer.WriteVarUhShort(m_objectiveId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_questId = reader.ReadVarUhShort();
            m_objectiveId = reader.ReadVarUhShort();
        }
    }
}
