//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Achievement
{
    using Common.Protocol.Network.Types.Game.Achievement;
    using System.Collections.Generic;
    using System;
    
    
    public class AchievementDetailsMessage : NetworkMessage
    {
        
        public const int Id = 6378;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private Achievement m_achievement;
        
        public virtual Achievement Achievement
        {
            get
            {
                return m_achievement;
            }
            set
            {
                m_achievement = value;
            }
        }
        
        public void Initiate(Achievement achievement)
        {
            m_achievement = achievement;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            m_achievement.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_achievement = new Achievement();
            m_achievement.Deserialize(reader);
        }
    }
}
