//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Achievement
{
    using System.Collections.Generic;
    using System;
    
    
    public class AchievementDetailsRequestMessage : NetworkMessage
    {
        
        public const int Id = 6380;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_achievementId;
        
        public virtual ushort AchievementId
        {
            get
            {
                return m_achievementId;
            }
            set
            {
                m_achievementId = value;
            }
        }
        
        public void Initiate(ushort achievementId)
        {
            m_achievementId = achievementId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhShort(m_achievementId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_achievementId = reader.ReadVarUhShort();
        }
    }
}
