//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Roleplay.Job
{
    using Common.Protocol.Network.Types.Game.Context.Roleplay.Job;
    using System.Collections.Generic;
    using System;
    
    
    public class JobCrafterDirectoryAddMessage : NetworkMessage
    {
        
        public const int Id = 5651;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private JobCrafterDirectoryListEntry m_listEntry;
        
        public virtual JobCrafterDirectoryListEntry ListEntry
        {
            get
            {
                return m_listEntry;
            }
            set
            {
                m_listEntry = value;
            }
        }
        
        public void Initiate(JobCrafterDirectoryListEntry listEntry)
        {
            m_listEntry = listEntry;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            m_listEntry.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_listEntry = new JobCrafterDirectoryListEntry();
            m_listEntry.Deserialize(reader);
        }
    }
}
