//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Actions.Fight
{
    using Common.Protocol.Network.Messages.Game.Actions;
    using System.Collections.Generic;
    using System;
    
    
    public class AbstractGameActionFightTargetedAbilityMessage : AbstractGameActionMessage
    {
        
        public const int Id = 6118;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private int m_targetId;
        
        public virtual int TargetId
        {
            get
            {
                return m_targetId;
            }
            set
            {
                m_targetId = value;
            }
        }
        
        private short m_destinationCellId;
        
        public virtual short DestinationCellId
        {
            get
            {
                return m_destinationCellId;
            }
            set
            {
                m_destinationCellId = value;
            }
        }
        
        private byte m_critical;
        
        public virtual byte Critical
        {
            get
            {
                return m_critical;
            }
            set
            {
                m_critical = value;
            }
        }
        
        private bool m_silentCast;
        
        public virtual bool SilentCast
        {
            get
            {
                return m_silentCast;
            }
            set
            {
                m_silentCast = value;
            }
        }
        
        public void Initiate(int targetId, short destinationCellId, byte critical, bool silentCast)
        {
            m_targetId = targetId;
            m_destinationCellId = destinationCellId;
            m_critical = critical;
            m_silentCast = silentCast;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteInt(m_targetId);
            writer.WriteShort(m_destinationCellId);
            writer.WriteByte(m_critical);
            writer.WriteBoolean(m_silentCast);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_targetId = reader.ReadInt();
            m_destinationCellId = reader.ReadShort();
            m_critical = reader.ReadByte();
            m_silentCast = reader.ReadBoolean();
        }
    }
}
