//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Actions.Fight
{
    using System.Collections.Generic;
    using System;
    
    
    public class GameActionFightSpellCastMessage : AbstractGameActionFightTargetedAbilityMessage
    {
        
        public const int Id = 1010;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_spellId;
        
        public virtual ushort SpellId
        {
            get
            {
                return m_spellId;
            }
            set
            {
                m_spellId = value;
            }
        }
        
        private byte m_spellLevel;
        
        public virtual byte SpellLevel
        {
            get
            {
                return m_spellLevel;
            }
            set
            {
                m_spellLevel = value;
            }
        }
        
        private List<System.Int16> m_portalsIds;
        
        public virtual List<System.Int16> PortalsIds
        {
            get
            {
                return m_portalsIds;
            }
            set
            {
                m_portalsIds = value;
            }
        }
        
        public void Initiate(ushort spellId, byte spellLevel, List<System.Int16> portalsIds)
        {
            m_spellId = spellId;
            m_spellLevel = spellLevel;
            m_portalsIds = portalsIds;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhShort(m_spellId);
            writer.WriteByte(m_spellLevel);
            writer.WriteShort(((short)(m_portalsIds.Count)));
            int portalsIdsIndex;
            for (portalsIdsIndex = 0; (portalsIdsIndex < m_portalsIds.Count); portalsIdsIndex = (portalsIdsIndex + 1))
            {
                writer.WriteShort(m_portalsIds[portalsIdsIndex]);
            }
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_spellId = reader.ReadVarUhShort();
            m_spellLevel = reader.ReadByte();
            int portalsIdsCount = reader.ReadUShort();
            int portalsIdsIndex;
            m_portalsIds = new System.Collections.Generic.List<short>();
            for (portalsIdsIndex = 0; (portalsIdsIndex < portalsIdsCount); portalsIdsIndex = (portalsIdsIndex + 1))
            {
                m_portalsIds.Add(reader.ReadShort());
            }
        }
    }
}
