//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Actions.Fight
{
    using Common.Protocol.Network.Messages.Game.Actions;
    using System.Collections.Generic;
    using System;
    
    
    public class GameActionFightActivateGlyphTrapMessage : AbstractGameActionMessage
    {
        
        public const int Id = 6545;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private short m_markId;
        
        public virtual short MarkId
        {
            get
            {
                return m_markId;
            }
            set
            {
                m_markId = value;
            }
        }
        
        private bool m_active;
        
        public virtual bool Active
        {
            get
            {
                return m_active;
            }
            set
            {
                m_active = value;
            }
        }
        
        public void Initiate(short markId, bool active)
        {
            m_markId = markId;
            m_active = active;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort(m_markId);
            writer.WriteBoolean(m_active);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_markId = reader.ReadShort();
            m_active = reader.ReadBoolean();
        }
    }
}
