//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Actions.Fight
{
    using Common.Protocol.Network.Messages.Game.Actions;
    using System.Collections.Generic;
    using System;
    
    
    public class GameActionFightTriggerGlyphTrapMessage : AbstractGameActionMessage
    {
        
        public const int Id = 5741;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private short m_markId;
        
        public virtual short MarkId
        {
            get
            {
                return m_markId;
            }
            set
            {
                m_markId = value;
            }
        }
        
        private int m_triggeringCharacterId;
        
        public virtual int TriggeringCharacterId
        {
            get
            {
                return m_triggeringCharacterId;
            }
            set
            {
                m_triggeringCharacterId = value;
            }
        }
        
        private ushort m_triggeredSpellId;
        
        public virtual ushort TriggeredSpellId
        {
            get
            {
                return m_triggeredSpellId;
            }
            set
            {
                m_triggeredSpellId = value;
            }
        }
        
        public void Initiate(short markId, int triggeringCharacterId, ushort triggeredSpellId)
        {
            m_markId = markId;
            m_triggeringCharacterId = triggeringCharacterId;
            m_triggeredSpellId = triggeredSpellId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort(m_markId);
            writer.WriteInt(m_triggeringCharacterId);
            writer.WriteVarUhShort(m_triggeredSpellId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_markId = reader.ReadShort();
            m_triggeringCharacterId = reader.ReadInt();
            m_triggeredSpellId = reader.ReadVarUhShort();
        }
    }
}
