//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Actions.Fight
{
    using System.Collections.Generic;
    using System;
    
    
    public class GameActionFightNoSpellCastMessage : NetworkMessage
    {
        
        public const int Id = 6132;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private uint m_spellLevelId;
        
        public virtual uint SpellLevelId
        {
            get
            {
                return m_spellLevelId;
            }
            set
            {
                m_spellLevelId = value;
            }
        }
        
        public void Initiate(uint spellLevelId)
        {
            m_spellLevelId = spellLevelId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhInt(m_spellLevelId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_spellLevelId = reader.ReadVarUhInt();
        }
    }
}
