//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Actions.Fight
{
    using Common.Protocol.Network.Messages.Game.Actions;
    using Common.Protocol.Network.Types.Game.Look;
    using System.Collections.Generic;
    using System;
    
    
    public class GameActionFightChangeLookMessage : AbstractGameActionMessage
    {
        
        public const int Id = 5532;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private int m_targetId;
        
        public virtual int TargetId
        {
            get
            {
                return m_targetId;
            }
            set
            {
                m_targetId = value;
            }
        }
        
        private EntityLook m_entityLook;
        
        public virtual EntityLook EntityLook
        {
            get
            {
                return m_entityLook;
            }
            set
            {
                m_entityLook = value;
            }
        }
        
        public void Initiate(int targetId, EntityLook entityLook)
        {
            m_targetId = targetId;
            m_entityLook = entityLook;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteInt(m_targetId);
            m_entityLook.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_targetId = reader.ReadInt();
            m_entityLook = new EntityLook();
            m_entityLook.Deserialize(reader);
        }
    }
}
