//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Actions.Fight
{
    using Common.Protocol.Network.Messages.Game.Actions;
    using System.Collections.Generic;
    using System;
    
    
    public class GameActionFightSlideMessage : AbstractGameActionMessage
    {
        
        public const int Id = 5525;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private int m_targetId;
        
        public virtual int TargetId
        {
            get
            {
                return m_targetId;
            }
            set
            {
                m_targetId = value;
            }
        }
        
        private short m_startCellId;
        
        public virtual short StartCellId
        {
            get
            {
                return m_startCellId;
            }
            set
            {
                m_startCellId = value;
            }
        }
        
        private short m_endCellId;
        
        public virtual short EndCellId
        {
            get
            {
                return m_endCellId;
            }
            set
            {
                m_endCellId = value;
            }
        }
        
        public void Initiate(int targetId, short startCellId, short endCellId)
        {
            m_targetId = targetId;
            m_startCellId = startCellId;
            m_endCellId = endCellId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteInt(m_targetId);
            writer.WriteShort(m_startCellId);
            writer.WriteShort(m_endCellId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_targetId = reader.ReadInt();
            m_startCellId = reader.ReadShort();
            m_endCellId = reader.ReadShort();
        }
    }
}
