//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Actions.Fight
{
    using Common.Protocol.Network.Messages.Game.Actions;
    using System.Collections.Generic;
    using System;
    
    
    public class GameActionFightExchangePositionsMessage : AbstractGameActionMessage
    {
        
        public const int Id = 5527;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private int m_targetId;
        
        public virtual int TargetId
        {
            get
            {
                return m_targetId;
            }
            set
            {
                m_targetId = value;
            }
        }
        
        private short m_casterCellId;
        
        public virtual short CasterCellId
        {
            get
            {
                return m_casterCellId;
            }
            set
            {
                m_casterCellId = value;
            }
        }
        
        private short m_targetCellId;
        
        public virtual short TargetCellId
        {
            get
            {
                return m_targetCellId;
            }
            set
            {
                m_targetCellId = value;
            }
        }
        
        public void Initiate(int targetId, short casterCellId, short targetCellId)
        {
            m_targetId = targetId;
            m_casterCellId = casterCellId;
            m_targetCellId = targetCellId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteInt(m_targetId);
            writer.WriteShort(m_casterCellId);
            writer.WriteShort(m_targetCellId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_targetId = reader.ReadInt();
            m_casterCellId = reader.ReadShort();
            m_targetCellId = reader.ReadShort();
        }
    }
}
