//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Actions.Fight
{
    using Common.Protocol.Network.Messages.Game.Actions;
    using System.Collections.Generic;
    using System;
    
    
    public class GameActionFightSpellCooldownVariationMessage : AbstractGameActionMessage
    {
        
        public const int Id = 6219;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private int m_targetId;
        
        public virtual int TargetId
        {
            get
            {
                return m_targetId;
            }
            set
            {
                m_targetId = value;
            }
        }
        
        private ushort m_spellId;
        
        public virtual ushort SpellId
        {
            get
            {
                return m_spellId;
            }
            set
            {
                m_spellId = value;
            }
        }
        
        private short m_value;
        
        public virtual short Value
        {
            get
            {
                return m_value;
            }
            set
            {
                m_value = value;
            }
        }
        
        public void Initiate(int targetId, ushort spellId, short value)
        {
            m_targetId = targetId;
            m_spellId = spellId;
            m_value = value;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteInt(m_targetId);
            writer.WriteVarUhShort(m_spellId);
            writer.WriteVarShort(m_value);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_targetId = reader.ReadInt();
            m_spellId = reader.ReadVarUhShort();
            m_value = reader.ReadVarShort();
        }
    }
}
