//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Actions.Fight
{
    using Common.Protocol.Network.Messages.Game.Actions;
    using System.Collections.Generic;
    using System;
    
    
    public class GameActionFightUnmarkCellsMessage : AbstractGameActionMessage
    {
        
        public const int Id = 5570;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private short m_markId;
        
        public virtual short MarkId
        {
            get
            {
                return m_markId;
            }
            set
            {
                m_markId = value;
            }
        }
        
        public void Initiate(short markId)
        {
            m_markId = markId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteShort(m_markId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_markId = reader.ReadShort();
        }
    }
}
