//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Actions.Fight
{
    using Common.Protocol.Network.Messages.Game.Actions;
    using System.Collections.Generic;
    using System;
    
    
    public class GameActionFightInvisibleObstacleMessage : AbstractGameActionMessage
    {
        
        public const int Id = 5820;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private uint m_sourceSpellId;
        
        public virtual uint SourceSpellId
        {
            get
            {
                return m_sourceSpellId;
            }
            set
            {
                m_sourceSpellId = value;
            }
        }
        
        public void Initiate(uint sourceSpellId)
        {
            m_sourceSpellId = sourceSpellId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhInt(m_sourceSpellId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_sourceSpellId = reader.ReadVarUhInt();
        }
    }
}
