//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Character.Creation
{
    using Common.Protocol.Network.Enums;
    using System.Collections.Generic;
    using System;
    
    
    public class CharacterCreationRequestMessage : NetworkMessage
    {
        
        public const int Id = 160;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private string m_name;
        
        public virtual string Name
        {
            get
            {
                return m_name;
            }
            set
            {
                m_name = value;
            }
        }
        
        private byte m_breed;
        
        public virtual byte Breed
        {
            get
            {
                return m_breed;
            }
            set
            {
                m_breed = value;
            }
        }
        
        private bool m_sex;
        
        public virtual bool Sex
        {
            get
            {
                return m_sex;
            }
            set
            {
                m_sex = value;
            }
        }
        
        private ushort m_cosmeticId;
        
        public virtual ushort CosmeticId
        {
            get
            {
                return m_cosmeticId;
            }
            set
            {
                m_cosmeticId = value;
            }
        }
        
        public void Initiate(string name, byte breed, bool sex, ushort cosmeticId)
        {
            m_name = name;
            m_breed = breed;
            m_sex = sex;
            m_cosmeticId = cosmeticId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteUTF(m_name);
            writer.WriteByte(m_breed);
            writer.WriteBoolean(m_sex);
            writer.WriteVarUhShort(m_cosmeticId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_name = reader.ReadUTF();
            m_breed = reader.ReadByte();
            m_sex = reader.ReadBoolean();
            m_cosmeticId = reader.ReadVarUhShort();
        }
    }
}
