//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Chat
{
    using System.Collections.Generic;
    using System;
    
    
    public class ChatServerCopyMessage : ChatAbstractServerMessage
    {
        
        public const int Id = 882;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private uint m_receiverId;
        
        public virtual uint ReceiverId
        {
            get
            {
                return m_receiverId;
            }
            set
            {
                m_receiverId = value;
            }
        }
        
        private string m_receiverName;
        
        public virtual string ReceiverName
        {
            get
            {
                return m_receiverName;
            }
            set
            {
                m_receiverName = value;
            }
        }
        
        public void Initiate(uint receiverId, string receiverName)
        {
            m_receiverId = receiverId;
            m_receiverName = receiverName;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhInt(m_receiverId);
            writer.WriteUTF(m_receiverName);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_receiverId = reader.ReadVarUhInt();
            m_receiverName = reader.ReadUTF();
        }
    }
}
