//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Chat
{
    using System.Collections.Generic;
    using System;
    
    
    public class ChatAbstractClientMessage : NetworkMessage
    {
        
        public const int Id = 850;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private string m_content;
        
        public virtual string Content
        {
            get
            {
                return m_content;
            }
            set
            {
                m_content = value;
            }
        }
        
        public void Initiate(string content)
        {
            m_content = content;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteUTF(m_content);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_content = reader.ReadUTF();
        }
    }
}
