//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Context.Roleplay.TreasureHunt
{
    using System.Collections.Generic;
    using System;
    
    
    public class TreasureHuntStepFollowDirectionToPOI : TreasureHuntStep
    {
        
        public const int Id = 461;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private byte m_direction;
        
        public virtual byte Direction
        {
            get
            {
                return m_direction;
            }
            set
            {
                m_direction = value;
            }
        }
        
        private ushort m_poiLabelId;
        
        public virtual ushort PoiLabelId
        {
            get
            {
                return m_poiLabelId;
            }
            set
            {
                m_poiLabelId = value;
            }
        }
        
        public void Initiate(byte direction, ushort poiLabelId)
        {
            m_direction = direction;
            m_poiLabelId = poiLabelId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteByte(m_direction);
            writer.WriteVarUhShort(m_poiLabelId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_direction = reader.ReadByte();
            m_poiLabelId = reader.ReadVarUhShort();
        }
    }
}
