//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Types.Game.Social
{
    using System.Collections.Generic;
    using System;
    
    
    public class GuildVersatileInformations : NetworkType
    {
        
        public const int Id = 435;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private uint m_guildId;
        
        public virtual uint GuildId
        {
            get
            {
                return m_guildId;
            }
            set
            {
                m_guildId = value;
            }
        }
        
        private uint m_leaderId;
        
        public virtual uint LeaderId
        {
            get
            {
                return m_leaderId;
            }
            set
            {
                m_leaderId = value;
            }
        }
        
        private sbyte m_guildLevel;
        
        public virtual sbyte GuildLevel
        {
            get
            {
                return m_guildLevel;
            }
            set
            {
                m_guildLevel = value;
            }
        }
        
        private sbyte m_nbMembers;
        
        public virtual sbyte NbMembers
        {
            get
            {
                return m_nbMembers;
            }
            set
            {
                m_nbMembers = value;
            }
        }
        
        public void Initiate(uint guildId, uint leaderId, sbyte guildLevel, sbyte nbMembers)
        {
            m_guildId = guildId;
            m_leaderId = leaderId;
            m_guildLevel = guildLevel;
            m_nbMembers = nbMembers;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhInt(m_guildId);
            writer.WriteVarUhInt(m_leaderId);
            writer.WriteSByte(m_guildLevel);
            writer.WriteSByte(m_nbMembers);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_guildId = reader.ReadVarUhInt();
            m_leaderId = reader.ReadVarUhInt();
            m_guildLevel = reader.ReadSByte();
            m_nbMembers = reader.ReadSByte();
        }
    }
}
