//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Context.Roleplay.Spell
{
    using System.Collections.Generic;
    using System;
    
    
    public class ValidateSpellForgetMessage : NetworkMessage
    {
        
        public const int Id = 1700;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_spellId;
        
        public virtual ushort SpellId
        {
            get
            {
                return m_spellId;
            }
            set
            {
                m_spellId = value;
            }
        }
        
        public void Initiate(ushort spellId)
        {
            m_spellId = spellId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhShort(m_spellId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_spellId = reader.ReadVarUhShort();
        }
    }
}
