//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Inventory.Exchanges
{
    using System.Collections.Generic;
    using System;
    
    
    public class ExchangeOnHumanVendorRequestMessage : NetworkMessage
    {
        
        public const int Id = 5772;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private uint m_humanVendorId;
        
        public virtual uint HumanVendorId
        {
            get
            {
                return m_humanVendorId;
            }
            set
            {
                m_humanVendorId = value;
            }
        }
        
        private ushort m_humanVendorCell;
        
        public virtual ushort HumanVendorCell
        {
            get
            {
                return m_humanVendorCell;
            }
            set
            {
                m_humanVendorCell = value;
            }
        }
        
        public void Initiate(uint humanVendorId, ushort humanVendorCell)
        {
            m_humanVendorId = humanVendorId;
            m_humanVendorCell = humanVendorCell;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhInt(m_humanVendorId);
            writer.WriteVarUhShort(m_humanVendorCell);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_humanVendorId = reader.ReadVarUhInt();
            m_humanVendorCell = reader.ReadVarUhShort();
        }
    }
}
