//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Inventory.Exchanges
{
    using System.Collections.Generic;
    using System;
    
    
    public class ExchangeOkMultiCraftMessage : NetworkMessage
    {
        
        public const int Id = 5768;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private uint m_initiatorId;
        
        public virtual uint InitiatorId
        {
            get
            {
                return m_initiatorId;
            }
            set
            {
                m_initiatorId = value;
            }
        }
        
        private uint m_otherId;
        
        public virtual uint OtherId
        {
            get
            {
                return m_otherId;
            }
            set
            {
                m_otherId = value;
            }
        }
        
        private byte m_role;
        
        public virtual byte Role
        {
            get
            {
                return m_role;
            }
            set
            {
                m_role = value;
            }
        }
        
        public void Initiate(uint initiatorId, uint otherId, byte role)
        {
            m_initiatorId = initiatorId;
            m_otherId = otherId;
            m_role = role;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhInt(m_initiatorId);
            writer.WriteVarUhInt(m_otherId);
            writer.WriteByte(m_role);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_initiatorId = reader.ReadVarUhInt();
            m_otherId = reader.ReadVarUhInt();
            m_role = reader.ReadByte();
        }
    }
}
