//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Inventory.Exchanges
{
    using Common.Protocol.Network.Types.Game.Data.Items;
    using System.Collections.Generic;
    using System;
    
    
    public class ExchangeShopStockMovementUpdatedMessage : NetworkMessage
    {
        
        public const int Id = 5909;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ObjectItemToSell m_objectInfo;
        
        public virtual ObjectItemToSell ObjectInfo
        {
            get
            {
                return m_objectInfo;
            }
            set
            {
                m_objectInfo = value;
            }
        }
        
        public void Initiate(ObjectItemToSell objectInfo)
        {
            m_objectInfo = objectInfo;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            m_objectInfo.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_objectInfo = new ObjectItemToSell();
            m_objectInfo.Deserialize(reader);
        }
    }
}
