//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Inventory.Exchanges
{
    using System.Collections.Generic;
    using System;
    
    
    public class ExchangeBidHousePriceMessage : NetworkMessage
    {
        
        public const int Id = 5805;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_genId;
        
        public virtual ushort GenId
        {
            get
            {
                return m_genId;
            }
            set
            {
                m_genId = value;
            }
        }
        
        public void Initiate(ushort genId)
        {
            m_genId = genId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhShort(m_genId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_genId = reader.ReadVarUhShort();
        }
    }
}
