//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Inventory.Exchanges
{
    using System.Collections.Generic;
    using System;
    
    
    public class ExchangeBidHouseGenericItemRemovedMessage : NetworkMessage
    {
        
        public const int Id = 5948;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private ushort m_objGenericId;
        
        public virtual ushort ObjGenericId
        {
            get
            {
                return m_objGenericId;
            }
            set
            {
                m_objGenericId = value;
            }
        }
        
        public void Initiate(ushort objGenericId)
        {
            m_objGenericId = objGenericId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhShort(m_objGenericId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_objGenericId = reader.ReadVarUhShort();
        }
    }
}
