//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Inventory.Exchanges
{
    using System.Collections.Generic;
    using System;
    
    
    public class ExchangeStartedWithStorageMessage : ExchangeStartedMessage
    {
        
        public const int Id = 6236;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private uint m_storageMaxSlot;
        
        public virtual uint StorageMaxSlot
        {
            get
            {
                return m_storageMaxSlot;
            }
            set
            {
                m_storageMaxSlot = value;
            }
        }
        
        public void Initiate(uint storageMaxSlot)
        {
            m_storageMaxSlot = storageMaxSlot;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            base.Serialize(writer);
            writer.WriteVarUhInt(m_storageMaxSlot);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            base.Deserialize(reader);
            m_storageMaxSlot = reader.ReadVarUhInt();
        }
    }
}
