//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Inventory.Exchanges
{
    using System.Collections.Generic;
    using System;
    
    
    public class ExchangeRequestMessage : NetworkMessage
    {
        
        public const int Id = 5505;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private byte m_exchangeType;
        
        public virtual byte ExchangeType
        {
            get
            {
                return m_exchangeType;
            }
            set
            {
                m_exchangeType = value;
            }
        }
        
        public void Initiate(byte exchangeType)
        {
            m_exchangeType = exchangeType;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteByte(m_exchangeType);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_exchangeType = reader.ReadByte();
        }
    }
}
