//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Inventory.Exchanges
{
    using Common.Protocol.Network.Types.Game.Data.Items;
    using System.Collections.Generic;
    using System;
    
    
    public class ExchangeStartedBidBuyerMessage : NetworkMessage
    {
        
        public const int Id = 5904;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private SellerBuyerDescriptor m_buyerDescriptor;
        
        public virtual SellerBuyerDescriptor BuyerDescriptor
        {
            get
            {
                return m_buyerDescriptor;
            }
            set
            {
                m_buyerDescriptor = value;
            }
        }
        
        public void Initiate(SellerBuyerDescriptor buyerDescriptor)
        {
            m_buyerDescriptor = buyerDescriptor;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            m_buyerDescriptor.Serialize(writer);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_buyerDescriptor = new SellerBuyerDescriptor();
            m_buyerDescriptor.Deserialize(reader);
        }
    }
}
