//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Inventory.Exchanges
{
    using System.Collections.Generic;
    using System;
    
    
    public class ExchangeShopStockMovementRemovedMessage : NetworkMessage
    {
        
        public const int Id = 5907;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private uint m_objectId;
        
        public virtual uint ObjectId
        {
            get
            {
                return m_objectId;
            }
            set
            {
                m_objectId = value;
            }
        }
        
        public void Initiate(uint objectId)
        {
            m_objectId = objectId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteVarUhInt(m_objectId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_objectId = reader.ReadVarUhInt();
        }
    }
}
