//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Protocol.Network.Messages.Game.Inventory.Exchanges
{
    using System.Collections.Generic;
    using System;
    
    
    public class JobBookSubscribeRequestMessage : NetworkMessage
    {
        
        public const int Id = 6592;
        
        public override int ProtocolId
        {
            get
            {
                return Id;
            }
        }
        
        private byte m_jobId;
        
        public virtual byte JobId
        {
            get
            {
                return m_jobId;
            }
            set
            {
                m_jobId = value;
            }
        }
        
        public void Initiate(byte jobId)
        {
            m_jobId = jobId;
        }
        
        public override void Serialize(ICustomDataWriter writer)
        {
            writer.WriteByte(m_jobId);
        }
        
        public override void Deserialize(ICustomDataReader reader)
        {
            m_jobId = reader.ReadByte();
        }
    }
}
